### PR TITLE
Param shift cv unreachable

### PR DESCRIPTION
**Pull request by dime10**
Fixes an unreachable code segment in the `qml.gradients.param_shift_cv` function.

`A.nonzero()` returns a tuple of arrays, where each array contains the indices to a non-zero element of A. Thus, if the length of the first index array is 1, then A must be 1-dimensional, making the first nested branch unreachable.

Finding a test case that actually triggers this branch turned out quite difficult, @josh146 would you happen to have an idea what kind of circuit would trigger it?
From my understanding the observable has to be second order, such as the `NumberOperator`. But the transformation by `Z` would have to be such that the only non-zero element is now at (0, 0).

### CODE REVIEW

**Review by josh146 — DISMISSED** [review]
Looks good @dime10, don't forget to update the changelog!

> Finding a test case that actually triggers this branch turned out quite difficult, @josh146 would you happen to have an idea what kind of circuit would trigger it?

You are right, this is _very_ hard to find. We would need the following things to line up:

- we have an observable `O` that is second order in the quadrature operators (e.g., using `NumberOperator` or `PolyXP`)

- there are operations _in-between_ the operator to be differentiated `U(x)` and the observable `O` represented by `V`

- Transforming `O` by `V` results in a new observable, `O'`, that _only contains an identity term_.

I think this could happen, but I can't say how/when 🤔

**Comment by dime10** [comment]
[sc-19266]

**Comment by dime10** [comment]
My bad, I think I misread the documentation for [np.nonzero](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html) thinking it worked like [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html).

However the problem of finding a test case for this branch remains 🤔

**Review by antalszava — APPROVED** [review]

**Comment by antalszava** [comment]
[sc-17362]

**Pull request merged**
