### PR TITLE
Make `Wires(None)` return empty Wires

### PR DESCRIPTION
**Pull request by astralcai**
**Context:**
`Wires(None)` returns `<Wires = [None]>`, requiring checks like `work_wires = Wires(work_wires) if work_wires is not None else Wires([])` in multiple places.

**Description of the Change:**
`Wires(None)` now returns `<Wires = []>`, simplifying code.

**Benefits:**
Cleaner code, one less thing to check for.

**Possible Drawbacks:**
It might break code for someone who uses `None` as a wire label for some reason

### CODE REVIEW

**Comment by timmysilv** [comment]
given sign-off from someone who has more of a say here, I approve!

**Comment by trbromley** [comment]
Thanks @astralcai! Going back to the discussion in the Slack channel: do we have the option of detecting if users are using `None` for a wire label and raising a deprecation warning? Is this PR blocking any other work?

**Comment by astralcai** [comment]
> Thanks @astralcai! Going back to the discussion in the Slack channel: do we have the option of detecting if users are using `None` for a wire label and raising a deprecation warning? Is this PR blocking any other work?

This is not blocking any other work. I consider it more a quality-of-life change for developers, but it shouldn't break anything. I don't think it's possible to detect whether a user is using `None` as a wire label just because of how Python works. If you set an optional argument and have the default be `None`, there is no way of knowing whether it is `None` because the user didn't specify anything, or if the user explicitly passed in `None`.

**Comment by timmysilv** [comment]
we should be able to deprecate in this case though, because `wires` is a required argument to the `Wires` [constructor](https://github.com/PennyLaneAI/pennylane/blob/f51e69589bb5571b361396a78689df1068c95023/pennylane/wires.py#L111). So we can say something like:
```python
if wires is None or (isinstance(wires, Sequence) and None in wires):
    warnings.warn("don't", qml.PennyLaneDeprecationWarning)
```

**Comment by astralcai** [comment]
> we should be able to deprecate in this case though, because `wires` is a required argument to the `Wires` [constructor](https://github.com/PennyLaneAI/pennylane/blob/f51e69589bb5571b361396a78689df1068c95023/pennylane/wires.py#L111). So we can say something like this right in the `Wires` class:
> 
> ```python
> if wires is None or (isinstance(wires, Sequence) and None in wires):
>     warnings.warn("don't", qml.PennyLaneDeprecationWarning)
> ```

So when creating `Wires` with `None`, instead of assuming there are no wires, raise a warning instead? This would catch the cases where `Wires([None])` are created accidentally, but if we do this, developers will still need to do things like `work_wires = Wires(work_wires) if work_wires is not None else Wires([])` every time.

**Comment by timmysilv** [comment]
exactly! If I'm understanding Tom correctly, he's proposing to do this deprecation in v0.36, then make this change in v0.37. Unfortunately, that means that until v0.37, we will have to do things like that every time.

**Comment by astralcai** [comment]
> exactly! If I'm understanding Tom correctly, he's proposing to do this deprecation in v0.36, then make this change in v0.37. Unfortunately, that means that until v0.37, we will have to do things like that every time.

@trbromley What do you think? If this is the plan I will close this PR.

**Pull request closed without merging**
