### PR TITLE
Fix vjp to work with nested params

### PR DESCRIPTION
**Pull request by thisac**
**Context:**
The vjp function does not return the expected values.

Without tape mode:
```pycon
>>> vjp = make_vjp(fun, x)
>>> vjp(np.array([1, 0, 0, 0]))
array([-0.654, 0.54])
```

The output of the VJP function should be of size 2, matching the input parameter size.

However, in tape mode, this is happening:
```pycon
>>> vjp = make_vjp(fun, x)
>>> vjp(np.array([1, 0, 0, 0]))
-0.654
```

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by josh146 — APPROVED** [review]
Really good catch @thisac!

I wonder if this is my usage of the `@`/`np.dot` product coming back to bite me... using `@` when I should really be doing 

```python
vjp = np.sum([i * j for i, j in zip(g, jac)], axis=0)
```

Two questions:

* Is it possible to construct an integration test for the `else` case in PL, to make sure that we catch this issue in PL rather than the plugin? Perhaps using `default.gaussian`?

* I was hoping this would fix the issue of ragged inputs not working, but it doesn't seem to be the case :(

**Review by trbromley — COMMENTED** [review]
Thanks @thisac! Looks good and makes sense - are we able to recreate this behaviour in PL core? :thinking: I guess we need for an element of `params` to be a list?
Agree that it might be nice to make a test for this.

**Comment by josh146** [comment]
> I guess we need for an element of params to be a list?

It's worse than that, we need a _trainable_ parameter to be a list/array. I'm not sure such an operation exists in PennyLane (all operations that accepts lists/arrays as parameters are non-differentiable), which is why it was only discovered in the GBSDevice.

**Comment by thisac** [comment]
Thanks @josh146 and @trbromley. As @josh146 touched upon, the only test I can think of adding is by using GBSDevice. I'm not sure if that's actually something we want to use in the PennyLane core tests.

**Pull request merged**
