### PR TITLE
Update the minimum version of Catalyst

### PR DESCRIPTION
**Pull request by rauletorresc**
**Description of the Change:** Update the minimum version of Catalyst.

### CODE REVIEW

**Comment by dime10** [comment]
This is too soon no?

**Comment by rauletorresc** [comment]
> This is too soon no?

I imagined that. But it is scheduled for Feature Freeze Monday according to the guide: https://github.com/PennyLaneAI/guidance-docs/blob/master/development/catalyst-release.md Although it says "Update if necessary" :)

- When do you consider it should be updated? 

I'll update the guide accordingly.

**Comment by dime10** [comment]
> > This is too soon no?
> 
> I imagined that. But it is scheduled for Feature Freeze Monday according to the guide: https://github.com/PennyLaneAI/guidance-docs/blob/master/development/catalyst-release.md Although it says "Update if necessary" :)
> 
> * When do you consider it should be updated?
> 
> I'll update the guide accordingly.

Yes you can open the PR I suppose but it can't be merged until a wheel with that version is available, or unless we disable the tests running PennyLane side. 

This is actually a tricky subject, but for now the PR can just stay here so we don't forget.

**Comment by astralcai** [comment]
This can probably be closed now.

**Comment by dime10** [comment]
I think it probably needs to be merged rather than closed, although it is true that it would have been better in the release

**Comment by astralcai** [comment]
I meant it is already in the release, see https://github.com/PennyLaneAI/pennylane/pull/5963

**Pull request closed without merging**
