### PR TITLE
Fixed bug in PauliRot where keyword args (theta and Pauli_word) were not being registered

### PR DESCRIPTION
**Pull request by Jaybsoni**
**Context:**
In the docs the call to PauliRot required 3 arguments `qml.PauliRot(theta, pauli_word, wires)`, but when calling these arguments through keywords we run into an error. 

This works 

```
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta, 'Z', wires=0)
    return qml.state()
```

But this didn't

```
@qml.qnode(dev)
def circuit(theta):
    qml.PauliRot(theta=theta, pauli_word='Z', wires=0)
    return qml.state()
```

**Description of the Change:**
Updated the `__init__` method to contain the same call signature as the documentation. 

**Related GitHub Issues:**
Link to issue: [1901](https://github.com/PennyLaneAI/pennylane/issues/1901)

### CODE REVIEW

**Comment by Jaybsoni** [comment]
[sc-11395]

**Comment by ankit27kh** [comment]
Hi, @Jaybsoni! I was looking around at other operations, and this seems to be a common issue. Perhaps there was a standard template using `*params`.
I don't know if this is intended or not.
I think it would have been better if all these operations used keyword arguments, or there should be a change in documentation.

**Review by antalszava — APPROVED** [review]
Looks good to me! Thank you for fixing this @Jaybsoni and for catching it @ankit27kh :rocket:

The issue would likely originate from the fact that we have `*params` in the signature for the `Operation` class.

This issue might arise with `QubitChannel` and `QubitUnitary` too (and potentially other operations?). Maybe it's good to create another issue such that we have this noted.

**Comment by ankit27kh** [comment]
@antalszava, this issue is widespread. I found many operations with similar problem. I have created an issue #1905

**Pull request merged**
