### PR TITLE
Update links in `qml.QNode` docstring

### PR DESCRIPTION
**Pull request by justinpickering**
Update qml.QNode documentation "main measurements page" links to point to Dynamic quantum circuits page.

**Context:**
- From slack message in #pennylane-oss-qa channel: https://xanaduhq.slack.com/archives/C0743CNS9E3/p1722451700797329.
- links for `main measurement page` in `mcm_method` and `postselect_mode` are inaccurate and should link to Dynamic quantum circuits page instead (https://docs.pennylane.ai/en/stable/introduction/dynamic_quantum_circuits.html#configuring-mid-circuit-measurements)

**Description of the Change:**
- Update "main measurements page" links in `mcm_method` and `postselect_mode` to point to Dynamic quantum circuits page (https://docs.pennylane.ai/en/stable/introduction/dynamic_quantum_circuits.html#configuring-mid-circuit-measurements)

**Benefits:**
- Users can get real usage details for those parameters

**Possible Drawbacks:**
N/A
**Related GitHub Issues:**
N/A

### CODE REVIEW

**Comment by justinpickering** [comment]
Hey @isaacdevlugt @trbromley - the "Documentation check / sphinx (pull_request)" is failing, do you happen to know how to fix this?

1. I linked to `/introduction/dynamic_quantum_circuits`, though would we prefer to link to the actual section `introduction/dynamic_quantum_circuits.html#configuring-mid-circuit-measurements`? If so, how should this be formatted to work?
2. I changed the hyperlink text from `main measurements page` to `dynamic quantum circuits page`. Please let me know if you have any other suggestions that may be more appropriate here.
3. The main  measurements page link for `mcm_method` is also mentioned in [qml.devices.qubit.simulate](https://docs.pennylane.ai/en/stable/code/api/pennylane.devices.qubit.simulate.html) documentation. Do we want to change it here too? This should be via the file [pennylane/devices/qubit/simulate.py](https://github.com/PennyLaneAI/pennylane/blob/docs-update-links/pennylane/devices/qubit/simulate.py)

**Comment by josh146** [comment]
@justinpickering from having a look at the CI logs, it appears it's because Sphinx cannot find the page: https://github.com/PennyLaneAI/pennylane/actions/runs/10187065237/job/28180274039?pr=6057#step:5:3263

```
qnode.py:docstring of pennylane.workflow.qnode.QNode:123: WARNING: unknown document: /introduction/dynamic_quantum_circuit
```

**Comment by josh146** [comment]
This is because the page is actually called `dynamic_quantum_circuits`

**Comment by justinpickering** [comment]
> This is because the page is actually called `dynamic_quantum_circuits`

Thank you for catching this @josh146 - I've updated the link!

**Review by isaacdevlugt — APPROVED** [review]
Thanks @justinpickering !

**Review by trbromley — APPROVED** [review]
Thanks @justinpickering!

Not a blocker for this PR, but I'd love to also fit in the fix on line 111:
```
a `variational circuit <https://pennylane.ai/qml/glossary/variational_circuit>`)__
```
i.e., with two underscores at the end to make the link work.

**Comment by justinpickering** [comment]
> Thanks @justinpickering!
> 
> Not a blocker for this PR, but I'd love to also fit in the fix on line 111:
> 
> ```
> a `variational circuit <https://pennylane.ai/qml/glossary/variational_circuit>`)__
> ```
> 
> i.e., with two underscores at the end to make the link work.

@trbromley - This has been updated in this PR, thanks!

**Pull request merged**
