### PR TITLE
Standardize eigvals to be floats

### PR DESCRIPTION
**Pull request by lillian542**
**Context:**
The dtype for `qml.sample(Identity(0))` doesn't match the dtype for its eigvals, and it breaks JAX-JIT. Some observables use `int`, some use `float`, depending on the dtype of `eigvals`. We're opting to standardize this to be floats.

**Description of the Change:**
Change eigvals of `X`, `Y`, `Z` and `Hadamard` to be floats. This will also affect `Tensor`, which previously was `int` if it was composed only of those observables.

The generation of samples is modified in `_qubit_device` and on `SampleMP`, because it wasn't actually using the `eigvals` for these 4 operators.

**Benefits:**
We can do this:
```
@qml.qnode(qml.device('default.qubit', shots=50))
def circuit(x):
    qml.RX(x, wires=0)
    return qml.sample(op=qml.I(0))
    
jax.jit(circuit)(jax.numpy.array(0.5))
```

and we are less likely to have similar/related bugs in the future.

**Possible Drawbacks:**
Samples that used to be `int` will become `float`

**Related GitHub Issues:**
#5369

### CODE REVIEW

**Comment by lillian542** [comment]
[sc-58742]

**Comment by trbromley** [comment]
Is this related to or replaced by https://github.com/PennyLaneAI/pennylane/pull/5607?

**Comment by lillian542** [comment]
> Is this related to or replaced by https://github.com/PennyLaneAI/pennylane/pull/5607?

Replacing, that one is old enough that I looked at the merge conflicts and decided it would be less work to just copy over the changes in a new PR instead and then start fixing tests

**Comment by lillian542** [comment]
Out of date, replaced by #5607

**Pull request closed without merging**
