### PR TITLE
[Code together] Creating a qft.py file in the subroutines folder

### PR DESCRIPTION
**Pull request by anonymousr007**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by rmoyard** [comment]
Thanks for the PR, we will review it soon. One thing you can already work on is removing the QFT operation and make sure that all tests pass with the QFT template.

**Comment by anonymousr007** [comment]
Hi @rmoyard, Basically all well but I am confused that why sphinx is failing so many times.

**Comment by rmoyard** [comment]
``` /github/workspace/pennylane/templates/subroutines/qft.py:docstring of pennylane.templates.subroutines.qft.QFT:5: WARNING: Unexpected indentation.
/github/workspace/pennylane/templates/subroutines/qft.py:docstring of pennylane.templates.subroutines.qft.QFT:6: WARNING: Literal block ends without a blank line; unexpected unindent.
/github/workspace/pennylane/templates/subroutines/qft.py:docstring of pennylane.templates.subroutines.qft.QFT:17: WARNING: Unexpected indentation.
/github/workspace/doc/code/qml_templates.rst:78:<autosummary>:1: WARNING: Inline substitution_reference start-string without end-string.
/github/workspace/doc/code/qml_templates.rst:78:<autosummary>:1: WARNING: Inline substitution_reference start-string without end-string.```

The problem probably comes from the following lines.

**Comment by anonymousr007** [comment]
`/github/workspace/doc/code/qml_templates.rst:78:<autosummary>:1: WARNING: Inline substitution_reference start-string without end-string.`

I corrected this one in my fork repo but how to pull this file in this pull request 😅

**Comment by antalszava** [comment]
Hi @anonymousr007, thank you for the submission! While reviewing, we've noticed that this work is very similar to another one that has already been submitted, in #1548.

Are you perhaps working together with @pratjz to solve this issue? If that's the case, it's best for the two of you to work on the same PR.

**Comment by anonymousr007** [comment]
Nope, I learned things in 1-2 days that's why I took some time to solve this issue 😅

**Comment by rmoyard** [comment]
Hi @anonymousr007, We are sorry but someone else was quicker and we've judt merged his PR. Nonetheless thank you for the contribution! You can still tackle another code together issue if you are interested 👍

**Pull request closed without merging**
