### PR TITLE
Limit python version to <1.24

### PR DESCRIPTION
**Pull request by AlbertMitjans**

### CODE REVIEW

**Review by albi3ro — APPROVED** [review]
changelog entry.

But thanks for getting on this so quickly.

**Comment by natestemen** [comment]
Was there a problem with numpy 1.24? We using 1.24 on Mitiq, and we can't currently upgrade to pennylane 0.28 due to dependency conflicts.

**Comment by josh146** [comment]
Hey @natestemen! The reason for limiting the NumPy version is that NumPy 1.24 removes the ability to _implicitly_ create ragged arrays. As this is something PennyLane requires at the moment, we have had to temporarily pin to numpy < 1.24.

Note that this is temporary; we are actively working to modify PL to work with numpy 1.24+ --- see https://docs.pennylane.ai/en/stable/code/api/pennylane.enable_return.html. As this is a breaking change to the PL UX, however, we are proceeding with care over several releases before making this default behaviour.

On your end, is there a reason for requiring NumPy 1.24?

**Comment by natestemen** [comment]
Thank you both for the information!

> On your end, is there a reason for requiring NumPy 1.24?

Actually, no. We've been in the habit of pinning our core dependencies quite strictly, but this has often made if hard for us to support the latest versions of _other_ dependencies. We've gone ahead and loosened the numpy requirement on our end, and pennylane 0.28 is now compatible. Thanks for spurring us to take a look at this.

**Pull request merged**
