### PR TITLE
Debug qubit device expval method with batch

### PR DESCRIPTION
**Pull request by JeremieGince**
**Context:** When utilizing a qubit device with batch processing, expval output, and BasisStateProjector, the probabilities were incorrectly indexed in the wrong dimension. This resulted in the expval output returning the probabilities of a vector within the batch, rather than providing the probabilities of the desired state for all entries in the batch.

**Description of the Change:** This pull request focuses on a specific modification—adjusting the indexing of probs from probs[idx] to probs[..., idx].

**Benefits:** This change enhances the functionality, allowing the use of batch processing with BasisStateProjector in expval.

**Possible Drawbacks:** There are currently no known drawbacks associated with this modification.

**Related GitHub Issues:** [#4975](https://github.com/PennyLaneAI/pennylane/issues/4975) .

### CODE REVIEW

**Comment by josh146** [comment]
Thanks for this PR @JeremieGince! Someone from the team will be on hand to review, but due to the holidays we may be a bit delayed on our end.

In the meantime, it looks like there are a [few tests failing](https://github.com/PennyLaneAI/pennylane/actions/runs/7305035650/job/19908102981?pr=4971) with this change; it looks like more complex logic may be required here in order to fix this bug and support shot vectors

**Comment by albi3ro** [comment]
Thanks for opening this fix @JeremieGince . 

Since this does seem to be a bug, would you mind opening an associated issue? This helps us keep track of what bugs have existed, where, and when.

**Comment by albi3ro** [comment]
Looking into this issue locally, I'm thinking the best fix might just be removing the specialized `BasisStateProjector` logic from `QubitDevice` and `ExpectationMP`.  

Everything works fine without that logic and we would have less to maintain.  I can't see why we added that specialized logic, or any benefit to having that logic there.

**Comment by JeremieGince** [comment]
Thank you very much to look at this PR with me. I just submit a new issue with a minimal non working example. I will try to remove the specialized BasisStateProjector logic from QubitDevice and ExpectationMP as you suggest and see if the tests all pass.

**Comment by albi3ro** [comment]
@JeremieGince This is a fairly high-priority bug, since PennyLane is giving wrong answers.  I'd like to get a fix in this week so that it can make it into the release that will be coming out next Monday night. Let me know if that timeline works for you.

**Comment by JeremieGince** [comment]
Thank you for taking care of this issue with your new PR. It's very appreciated.

**Pull request closed without merging**
