### PR TITLE
Prevent Hamiltonians that share wires from being multiplied together

### PR DESCRIPTION
**Pull request by trbromley**
Raises a `ValueError` if Hamiltonians sharing wires are multiplied together:

```python
h1 = qml.Hamiltonian([1, 1], [qml.PauliZ(0), qml.PauliZ(1)])
h1 @ h1
```
This will raise a `ValueError`.

Fixes https://github.com/PennyLaneAI/pennylane/issues/1272 although this is just to help prevent users getting caught-out, we still need a better solution for manipulation of Hamiltonians.

### CODE REVIEW

**Review by glassnotes — APPROVED** [review]
Looks good! :+1: In the long term, maybe `@` can call `grouping.pauli_mult` for cases like this (though I think there would be some things to iron out in terms of wire maps -- perhaps @josh146 can speak further to this, he pointed it out while reviewing #1181).

**Comment by josh146** [comment]
> Looks good! 👍 In the long term, maybe `@` can call grouping.pauli_mult for cases like this (though I think there would be some things to iron out in terms of wire maps -- perhaps @josh146 can speak further to this, he pointed it out while reviewing #1181).

Alternatively, is there anything stopping us from having `__matmul__` call `grouping.pauli_mult` in the short term? 🙂 It might solve a lot of open issues we have on operator multiplication

**Comment by anthayes92** [comment]
Nice short term solution! A long term fix for this would render [1213](https://github.com/PennyLaneAI/pennylane/pull/1213) obselete.

**Review by anthayes92 — APPROVED** [review]

**Comment by glassnotes** [comment]
> > Looks good! +1 In the long term, maybe `@` can call grouping.pauli_mult for cases like this (though I think there would be some things to iron out in terms of wire maps -- perhaps @josh146 can speak further to this, he pointed it out while reviewing #1181).
> 
> Alternatively, is there anything stopping us from having `__matmul__` call `grouping.pauli_mult` in the short term? slightly_smiling_face It might solve a lot of open issues we have on operator multiplication

Which `__matmul__`, the one in the `Hamiltonian` class? I think as long as a consistent wire map is chosen it should be fine (and we could make a like a cumulative wire map using the shared wires of all the terms, or even make it an argument to the Hamiltonian itself.).

**Pull request merged**
