### PR TITLE
Qutrit/Qudit Channel

### PR DESCRIPTION
**Pull request by MashAliK**
**Context:**
Introduces `QuditChannel` by generalizing the existing `QubitChannel` and creates another class, `QutritChannel`, for handling 3x3 Kraus Matrices. Now, `QubitChannel` and `QutritChannel` are both classes that inherit from `QuditChannel` and they work on their respective mixed-state device.

**Description of the Change:**

- `QuditChannel` introduced into `pennylane/ops/channel.py` and existing code for `QubitChannel` is moved into this class and modified to handle arbitrary dimensions.
- `QutritChannel` introduced into `pennylane/ops/channel.py` and is a subclass of `QuditChannel`.
- `TestQutritChannel` introduced into `tests/ops/test_channel_ops.py` to verify correct output (single and multiple wires), correct input of Kraus Matrices, and that circuits with `qml.QutritChannel` are differentiated correctly.

**Benefits:**
Creating the general `QuditChannel` class reduces duplicate code and makes development and debugging easy for future updates by keeping the code in one place.

**Possible Drawbacks:**

**Related GitHub Issues:**
https://github.com/PennyLaneAI/pennylane/issues/5649

### CODE REVIEW

**Review by mudit2812 — COMMENTED** [review]
Hey @MashAliK ! Great work on your PR! I've left a review, but [Another PR](https://github.com/PennyLaneAI/pennylane/pull/5793) is in a state that’s closer to the finish line for us. As a result, we will delegate priority to that PR to see it through and may not review yours further. It might still be worthwhile to complete your attempt in case something falls through, but we can’t guarantee that we’ll go with your work at this stage.

If you’d like, you can check out our other bounties that are still up for grabs [here](https://github.com/PennyLaneAI/pennylane/labels/unitaryhack). Thanks so much for your hard work and interest in PennyLane!

**Comment by MashAliK** [comment]
> Hey @MashAliK ! Great work on your PR! I've left a review, but [Another PR](https://github.com/PennyLaneAI/pennylane/pull/5793) is in a state that’s closer to the finish line for us. As a result, we will delegate priority to that PR to see it through and may not review yours further. It might still be worthwhile to complete your attempt in case something falls through, but we can’t guarantee that we’ll go with your work at this stage.
> 
> If you’d like, you can check out our other bounties that are still up for grabs [here](https://github.com/PennyLaneAI/pennylane/labels/unitaryhack). Thanks so much for your hard work and interest in PennyLane!

Thanks for the review! I do have some changes and bug fixes that would need to be made so I will let the other PR wrap this one up. I'll just leave this PR open for now in case anything comes up.

**Comment by trbromley** [comment]
Thanks @MashAliK for opening this PR. With https://github.com/PennyLaneAI/pennylane/pull/5793 closing the issue, it might make sense to close this PR.

**Comment by mudit2812** [comment]
Thanks again for opening this PR @MashAliK ! Closing this now.

**Pull request closed without merging**
