### PR TITLE
[Code Together] Categorizing the qubit gates in the documentation #1566

### PR DESCRIPTION
**Pull request by Pratul-Saini**
**Description of the Change:** The documentation in [pennylane/doc/introduction/operations.rst](https://github.com/PennyLaneAI/pennylane/blob/master/doc/introduction/operations.rst) has been updated to mirror the code in [pennylane/ops/qubit](https://github.com/PennyLaneAI/pennylane/tree/master/pennylane/ops/qubit). Specifically, `Qubit Gates` has been divided into categories that already exist and other new categories.

**Benefits:** The documentation is now more in line with the code and hence operations will be easier to find.

**Related GitHub Issues:** #1566

### CODE REVIEW

**Comment by Pratul-Saini** [comment]
Note, a previous pull request was closed since I felt like I had made it too cluttered so I [closed it](https://github.com/PennyLaneAI/pennylane/pull/1583) and have created this one instead. Sorry if this caused confusion

**Comment by antalszava** [comment]
Hi @Pratul-Saini, that's okay! :) Let us know if once you'd like us to have a review on this one.

**Comment by Pratul-Saini** [comment]
Hi @antalszava. Thanks for your kind reply. I believe it is ready to go.

**Review by albi3ro — APPROVED** [review]
Thanks 🎉 💯 

An approval from me. Good job.

**Pull request merged**
