### PR TITLE
Update stable dependencies on schedule

### PR DESCRIPTION
**Pull request by mudit2812**
As name says. Currently, every time stable dependencies change (every time a PR is merged to master), an automatic PR is opened to update the dependencies. It can be quite annoying to merge a PR and then another one gets opened immediately afterwards. Thus, this changes the test workflows to run them on a weekly schedule, and a PR to update stable dependencies is only opened if the test workflow is triggered by the schedule.

All changes have been implemented by @timmysilv . I'm just the messenger.

### CODE REVIEW

**Review by timmysilv — APPROVED** [review]
wow so elegant. 10/10. i approve of this message 👍

**Review by Alex-Preciado — APPROVED** [review]
Nice!! 😎

**Comment by timmysilv** [comment]
PS for people were curious about crontab syntax: I recommend [crontab.guru](https://crontab.guru/) if you ever need a refresher

**Comment by mudit2812** [comment]
[sc-72363]

**Pull request merged**
