### PR TITLE
Fix parameter counting in `DefaultQubitLegacy` adjoint method

### PR DESCRIPTION
**Pull request by dwierichs**
**Context:**
The adjoint method of `DefaultQubitLegacy` uses two incompatible ways to quantify tape parameters: It sets up the number of tape parameters correctly using `tape.get_parameters(trainable_only=False)` but checks whether an operation comes with a parameter via `grad_method is not None`. This lead to a bug where, for example, `QubitUnitary` disrupts the parameter counting.

**Description of the Change:**
As all operations with more than one parameter are being decomposed/raised an error upon anyways,  this PR changes the way to detect parametrized operations to `op.num_params==1`.

**Benefits:**
Bug fix: Correct adjoint method derivatives even when using `QubitUnitary` and other operations that have `grad_method=None` but have parameters.

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
N/A

### CODE REVIEW

**Comment by dwierichs** [comment]
@vincentmr This is the PR (sorry, took a moment to figure this out after all)

**Review by albi3ro — COMMENTED** [review]
Even though its currently not causing issues, mind fixing this as well in the new system:

https://github.com/PennyLaneAI/pennylane/blob/52b9f5cd1340f4aca01f70c2eeb59f6a9251deec/pennylane/devices/qubit/adjoint_jacobian.py#L83

https://github.com/PennyLaneAI/pennylane/blob/52b9f5cd1340f4aca01f70c2eeb59f6a9251deec/pennylane/devices/qubit/adjoint_jacobian.py#L160

https://github.com/PennyLaneAI/pennylane/blob/52b9f5cd1340f4aca01f70c2eeb59f6a9251deec/pennylane/devices/qubit/adjoint_jacobian.py#L235

**Comment by dwierichs** [comment]
>Even though its currently not causing issues, mind fixing this as well in the new system:

@albi3ro Done :)

**Review by timmysilv — APPROVED** [review]
great find, and simple fix!

**Review by albi3ro — APPROVED** [review]
👍 Thanks for getting this together so quickly.

**Pull request merged**
