### PR TITLE
Drop python 3.8 & update Jax to 0.4.14

### PR DESCRIPTION
**Pull request by rmoyard**
**Description of the Change:**

- Remove python 3.8
- Update Jax version on the CI checks.

### CODE REVIEW

**Comment by rmoyard** [comment]
[sc-37949]

**Review by mudit2812 — APPROVED** [review]
Thanks Romain! Could you open a PR on the `pennylane.ai-react` repo with the update as well? You can see an example here https://github.com/XanaduAI/pennylane.ai-react/pull/371

**Comment by mlxd** [comment]
Hey @rmoyard, since the docs-builder also installs PennyLane under 3.8, can you update the python version there too to 3.9?

Once this goes through I'll update the expected CI requirements in the repo

**Review by mlxd — APPROVED** [review]
Thanks @rmoyard !

**Pull request merged**
