### PR TITLE
[Code Together] solve issue More informative QNode diff_method #1399

### PR DESCRIPTION
**Pull request by ankit27kh**
------------------------------------------------------------------------------------------------------------

**Context:**
[Code Together]

**Description of the Change:**
diff_method attribute of QNode will be updated after a method has been selected if it was earlier "best".

**Benefits:**
Gives information about diff_method much more easily.

**Possible Drawbacks:**
None

**Related GitHub Issues:**
#1399

### CODE REVIEW

**Comment by ankit27kh** [comment]
I am very new to this. Not sure what needs to be done next.

**Comment by ankit27kh** [comment]
test failed. will try again later

**Comment by antalszava** [comment]
Hi @ankit27kh, let us know if you'd have any questions along the way!

**Comment by ankit27kh** [comment]
I have actually!
if you see the qnode.py file, if diff_method is selected as "parameter-shift", we get the tape and change the method to "analytic".
```
if diff_method == "parameter-shift":
            return (
                QNode._get_parameter_shift_tape(device),
                interface,
                device,
                {"method": "analytic"},
            )
```

but if the method is "best" and the best method selected is parameter shift, the method is changed to "best"!?
```
return (
                        QNode._get_parameter_shift_tape(device),
                        interface,
                        device,
                        {"method": "best"},
                    )
```
Why is this change?
The test file also expects "best" if initially, it was "best" but "analytic" if initially, it was "parameter-shift".

**Comment by antalszava** [comment]
Hi @ankit27kh, that's a good question! I believe that the answer is related to the analytic gradient of each gate within the circuit.

If the user specifies `diff_method="best"` and that resolves to use the parameter-shift rule based on the device and interface, it might be, that some operations in the circuit still do not support the parameter-shift rule. In such cases, we'll be falling back to finite differences, when performing the computation.

If the user specifies `diff_method="parameter-shift"` and there are some operations in the circuit that do not support the parameter-shift rule, then we won't fall back to finite differences, but instead will raise an error.

All in all, the first case, with `diff_method="best"` is "safer" for the user, as PennyLane will attempt to perform the computation, even if that means falling back to a less favourable case.

CC-ing @josh146 here too, maybe he has more on this.

**Comment by josh146** [comment]
What @antalszava has covered most of it above 🙂 The only thing I might add is that `best` currently defaults to `backprop` as first priority, if the underlying device supports backprop.

**Comment by josh146** [comment]
@antalszava what you say above covers it well 🙂 Essentially:

- `best`: Choose parameter-shift if possible. If there are gates that do not support parameter shift, fall back to finite-differences. Useful if you want the gradient on hardware, but don't really mind how. PL will try to use the best approach per-gate.

- `parameter-shift`: _only_ use parameter-shift. If not possible, raise an error. Useful if you want to ensure accuracy and avoid numeric issues with finite-differences.

- `finite-diff`: _only_ use finite-differences.

**Pull request closed without merging**
