### PR TITLE
Always draw with device wires first

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
Sometimes, tapes will use standard wires (eg. `[0, 1, 2]`) but will report them out of order, depending on the order in which they are used. If we are drawing a qnode (in other words, a circuit bound to a device), we have the true wire order available to us.

**Description of the Change:**
Use the device wire order wherever possible in drawing logic

**Benefits:**
We don't accidentally draw in funky wire orders like `[1, 0]`. See the docstring that I changed in `tape_expand` as an example (before this PR, it would swap wires without the `wire_order` specified)

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
first found in #4711

### CODE REVIEW

**Review by mudit2812 — COMMENTED** [review]
Could this also be problematic for all-wire measurement processes when executing qnodes? For example if a tape has wires `[1, 0, 2]`, that will be the wire order with which `qml.state()`, `qml.probs()`, `qml.sample()`, and `qml.counts()` use.

**Review by mudit2812 — APPROVED** [review]
Other than that the changes look good. My comments are out of scope for this PR.

**Comment by timmysilv** [comment]
it won't be a problem, because those tapes (eg. tape with wires=`[1, 0, 2]`) aren't computed out of order, they're just drawn out of order. For example, take a look here:
```pycon
>>> qs = qml.tape.QuantumScript([qml.CNOT([1, 0])])
>>> qs.wires, qs.map_to_standard_wires() is qs
(<Wires = [1, 0]>, True)
```
The mapped version of the tape is itself. In other words, we consider this "standard" in `simulate.py`, so no re-ordering is done, and the tape is executed on the naturally expected wires.

**Comment by trbromley** [comment]
> If we are drawing a qnode (in other words, a circuit bound to a device), we have the true wire order available to us.

Do you mean the wire order that comes from the device? How will this work with the new device API?

**Comment by timmysilv** [comment]
indeed. if the device wires exist, we should use them. it just tries these from highest to lowest priority:
1. if `wire_order` is provided, use it
2. elif `qnode.device.wires` is defined, use it
3. else use `tape.wires`

**Pull request merged**
