### PR TITLE
[unitaryHACK] Enable non-Hermitian operator to be defined

### PR DESCRIPTION
**Pull request by brs96**
**Context:**
Enable non-Hermitian operator to be defined

**Description of the Change:**
Enable non-Hermitian operator to be defined with relevant tests.

**Benefits:**
Custom non-Hermitian operator can be defined, e.g:
```python
        class NewOp(qml.operation.Operator):
            num_wires = 2
            num_params = 1
            par_domain = "L"

        non_hermitian_op = NewOp(np.array([[1j, 0], [0, -1j]]), wires=[0, 1])
```

**Possible Drawbacks:**
Operator with incorrect matrices can be defined/initialized, exception is only returned when matrix method is called.

**Related GitHub Issues:**
#1120

### CODE REVIEW

**Comment by josh146** [comment]
Thanks for this great contribution @brs96! Someone from the team will be on hand shortly to provide a review, let us know if you have any questions in the meantime. Don't forget to add a commit to update the changelog (`.github/CHANGELOG.md`) :)

**Comment by ixfoduap** [comment]
Hi @brs96, thank you for this submission!

I'm afraid that I don't fully understand the purpose of this pull request. What exactly was the issue that these changes are trying to fix? Do you have a concrete example showing errors arising when defining a non-Hermitian operator? I find this surprising since several of the supported operations in PennyLane are not Hermitian, e.g. the [PhaseShift](https://pennylane.readthedocs.io/en/latest/code/api/pennylane.PhaseShift.html) gate.

As far as I can tell, you are changing the `Operator()` base class so that the `_matrix()` method is explicitly defined, plus a couple of checks that the matrix is unitary and square. How does this help address the issue?

Thanks!

**Comment by brs96** [comment]
https://github.com/PennyLaneAI/pennylane/issues/1120
There're many operations/observables that have non-Hermitian matrix, but no easy way to define an arbitrary non-hermitian operator, directly from Operator class.
From #1120 this change is needed to allow @ between operators that give non-hermitian result?
The suggestion in #1120 : op = Operator(matrix=mx, wires=wires) is one line, the change in PR requires defining a class first (to keep num_wires, num_params, par_domain abstract), but happy to change it.

Let me know if I interpreted 1120 wrongly...

Thanks!

**Comment by antalszava** [comment]
Hi @brs96, thank you for picking this up and looking into this! :100: :slightly_smiling_face:  Your questions are completely in place! After a bit more consideration defining a non-Hermitian operator still requires more exploration to get the design right and would be less fit as a first issue. Therefore maybe it's better to have the proposal be closed for now, but your approach definitely gives ideas for the exploration process.

On another note, there are still nice places to contribute which are also part of unitaryHACK! :slightly_smiling_face: We've recently added a new unitaryHACK issue for adding the `IsingYY` operation from one of the existing PennyLane plugins:
https://github.com/PennyLaneAI/pennylane/issues/1347

There were 2 other Ising operations added recently, so the approach could be followed nicely. :slightly_smiling_face: 

If you'd be more interested in tackling something else, here is the [entire list for the unitaryHACK issues](https://github.com/PennyLaneAI/pennylane/issues?q=is%3Aopen+is%3Aissue+label%3Aunitaryhack) that we have.

**Comment by brs96** [comment]
Sure, np, I see why doing this may not be the best to just allow @ well-defined/closed over non-hermitian, will check the other issues.

**Pull request closed without merging**
