### PR TITLE
[Code Together] Change the order of technical description and list of functions in the documentation

### LINKED ISSUE #1365: Change order of technical description and list of functions in documentation
Three modules, [`kernels`](https://pennylane.readthedocs.io/en/latest/code/qml_kernels.html), [`grouping`](https://pennylane.readthedocs.io/en/latest/code/qml_grouping.html), and [`qaoa`](https://pennylane.readthedocs.io/en/latest/code/qml_qaoa.html) have their module documentation ordered such that there is first a lengthy description of the theory, and the actual list of functions comes after. We should update the docs of these modules so that the functions appear *first*, and the technical details come afterwards (as was recently discussed in #1160). This will improve readability of the documentation and make it easier to find the details of a desired function.

### PR DESCRIPTION
**Pull request by AkashNarayanan**
**Description of the Change:**
The documentation of `qml.grouping`, `qml.kernels` and `qml.qaoa` modules have been updated to present the list of functions first followed by the technical details of the module.

**Rendered Pages:**
- [qml.grouping](https://pennylane--1581.org.readthedocs.build/en/1581/code/qml_grouping.html)
- [qml.kernels](https://pennylane--1581.org.readthedocs.build/en/1581/code/qml_kernels.html)
- [qml.qaoa](https://pennylane--1581.org.readthedocs.build/en/1581/code/qml_qaoa.html)

**Benefits:**
Improves readability of the documentation.

**Related GitHub Issues:**
Closes #1365

### CODE REVIEW

**Comment by antalszava** [comment]
Hi @AkashNarayanan, thank you for opening the PR! :slightly_smiling_face: We've tagged the original issue for Code Together, let us know if we can help in some way with this.

**Comment by AkashNarayanan** [comment]
Hi @antalszava ! I have already submitted a PR (#1546) for another Code Together issue (#1531) and it has been merged. Is it alright to proceed with this PR?

**Comment by antalszava** [comment]
Hi @AkashNarayanan, definitely! 🙂 It's okay to submit multiple solutions in Code Together. 🎉

**Comment by AkashNarayanan** [comment]
Hi @antalszava ! I am not sure why the documentation check is failing. Can you please help me with this problem?

**Review by antalszava — APPROVED** [review]
Looks good to me! :100: Thank you for this addition @AkashNarayanan, handy to have the docs be in better shape. :tada: :slightly_smiling_face:

**Pull request merged**
