### PR TITLE
[queuing] move the RLock from QuantumTape to AnnotatedQueue

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
`QuantumTape` has a class-level RLock to ensure parallel tapes don't queue each other's contents. This wasn't ported to `AnnotatedQueue` because we failed to replicate the issue when porting contents over, but I recently confirmed that the issue still exists with `AnnotatedQueue`.

**Description of the Change:**
Move the RLock from `QuantumTape` to `AnnotatedQueue`.

**Benefits:**
Any parallel queuing, regardless of type, will be guaranteed to not overlap with each other.

**Possible Drawbacks:**
There's the lock-acquisition overhead which won't be relevant in the majority of cases when users aren't multi-threading.

**Related GitHub Issues:**
Reoccurrence of #910

A minimal example of the issue (which I add as a unit test in this PR):
```python
import pennylane as qml
from multiprocessing.dummy import Pool as ThreadPool
q1 = qml.queuing.AnnotatedQueue()
q2 = qml.queuing.AnnotatedQueue()
def queue_pauli(arg):
    q, pauli = arg
    with q:
        for _ in range(10000):
            pauli(0)
args = [(q1, qml.PauliX), (q2, qml.PauliY)]
ThreadPool(2).map(queue_pauli, args)
[(all(isinstance(op, expected_op) for op in queue.queue), len(queue)) for queue, expected_op in args]
```

### CODE REVIEW

**Comment by josh146** [comment]
@timmysilv is there somewhere we can keep/store knowledge of the minimal-non-working example you have in the PR comment?

We have 'forgotten' how to reproduce this multiple times in the past, and wondering how we can avoid this in the future 😆

**Comment by timmysilv** [comment]
I'll add it as a test! if someone is poking through the git blame, they should find this PR.

**Comment by mlxd** [comment]
Hey folks, I think the problem here is the wrong datastructure design, rather than a need for adding locks to existing code.

The in-built Python queue is already thread-safe, so we should be using that as part of the process, rather than locking our own DS. I'll think more about this, but I'd rather avoid any locking code if we can avoid it at our development level, and especially when using Python --- given the existing implementations can handle this for us.

**Comment by mlxd** [comment]
> to be clear on the timeline:
> 
>     1. original QuantumTape didn't have locks, race condition happened
> 
>     2. bug was closed when external user (who found the RC) submitted a fix
> 
>     3. We split QuantumTape into AnnotatedQueue+QuantumScript, but did NOT take the RLock
> 
>     4. I'm realizing that was a mistake (or at least, a regression)
> 
> 
> That said, I agree that we can do better than an RLock here. Just making sure that it's understood that this PR is re-introducing old code (and not proposing new stuff).
> 
> Do we want to hold off on this while investigating more? In my opinion, the change is pretty small in terms of LOC, and I'd most want to have (more) correct queuing in the next release.

Just chatted with @josh146  --- it may make sense to create a bugfix release for this ASAP to avoid the problem appearing in the released 0.29.x branch. We can discuss the details of removing this then for 0.30. @albi3ro that work for your timeline too?

**Comment by timmysilv** [comment]
I proposed something different in the PR linked right above this comment. Rather than using an RLock, I essentially make `QueuingManager._active_contexts` get stored in thread-local memory. I'm not sure if this is better, but I've put up a PR to open discussion

**Review by albi3ro — APPROVED** [review]
Given this solves the problem and simply uses the pre-existing solution that existed in a different piece of code, let's proceed with this option.

**Comment by timmysilv** [comment]
hi @PennyLaneAI/performance 👋 

tagging y'all for review because it might affect you most/you'll have the most context on this. tl;dr, a user discovered a while back that if you have multiples tapes queuing in parallel, they will accidentally queue the wrong stuff. So, we added a `threading.RLock` that tapes acquire upon context entry. We did not move that to `AnnotatedQueue` when making that class, but we should have, because it has the same problem. This PR moves the lock from `QuantumTape` (which is now only a user-convenience thing) to `AnnotatedQueue` (which is the underlying queuing object used by everything including QNodes).

I considered something else (like putting queues in thread-local memory) but we decided to not introduce new stuff yet, and first fix what's wrong. We'd actually most prefer to get rid of queuing altogether. One day...

**Review by mlxd — APPROVED** [review]
Hi @timmysilv 
Based on previous discussions around this, let's forge ahead with the fix here and define another approach later down the road.

**Pull request merged**
