### PR TITLE
Allow `Hamiltonian` and `Sum` observables in sample measurements

### PR DESCRIPTION
**Pull request by eddddddy**
**Context:**
Part of the effort to integrate the new device API. Support for sample-based measurements was recently added, though currently it doesn't allow for `Hamiltonian` and `Sum` observables.

**Description of the Change:**
Extend the `measure_with_samples` function to be able to handle these cases. We simply sum over the results for each term in the object.

**Benefits:**
The user can now use `Hamiltonian` and `Sum` observables with finite shots. 🎉 

**Possible Drawbacks:**
None

### CODE REVIEW

**Comment by eddddddy** [comment]
[sc-38634]

**Review by albi3ro — COMMENTED** [review]
Let's add some heftier tests to make sure things are still looking good at higher qubit numbers.

There's this example that I've been reusing in for the "higher qubit" regime: 
```
n_wires = 10
scale = 0.5 # for testing derivatives
offset = 0.1

ops = [qml.RX(offset + scale*i, wires=i) for i in range(n_wires)]

t1 = 2.5 * qml.prod(*(qml.PauliZ(i) for i in range(n_wires)))
t2 = 6.2 * qml.prod(*(qml.PauliY(i) for i in range(n_wires)))
H = t1+t2


phase = offset + scale * np.array(range(n_wires))
cosines = qml.math.cos(phase)
sines = qml.math.sin(phase)
expected = 2.5 * qml.math.prod(cosines) + 6.2 * qml.math.prod(sines)
```

We could potentially also have a more complicated hamiltonian and compare between sampling and `shots=None` so that we can have more validation for more complicated sitautions.

**Review by albi3ro — COMMENTED** [review]
Also, I had to change [`sample.py` Line 229](https://github.com/PennyLaneAI/pennylane/blob/2f89be4899d16d256cb71dda998f446489b61a6f/pennylane/measurements/sample.py#LL229C1-L229C1) to get this working on larger hamiltonians.

`Tensor.name` being a list causes problems again... at least comparing with `str(name)` fixes the problem.

**Review by albi3ro — APPROVED** [review]
Thanks!

**Comment by albi3ro** [comment]
> I have a question that might lie out of scope for this PR, but relates to Sum vs. Hamiltonian. Suppose someone is measuring the expectation of 2.2XY+2.2ZX. this may be expressed as either:
> 
> * `qml.sum(qml.s_prod(2.2, qml.prod(qml.PauliX(0), qml.PauliY(1))), qml.s_prod(2.2, qml.prod(qml.PauliZ(0), qml.PauliX(1))))`
> * `qml.s_prod(2.2, qml.sum(qml.prod(qml.PauliX(0), qml.PauliY(1)), qml.prod(qml.PauliZ(0), qml.PauliX(1)))`
> 
> Are we assuming that the user will always do the first one (ie. a neatly organized sum of products with scalar coeffs applied to each term)? I ask because the former will be handled nicely with this change, but the latter will not (I think..). Deeply nested arithmetic ops can make everything messy, so I'm wondering if we should explicitly limit support for them

Good point. One way we could fix this is by throwing on a pass of `qml.simplify` either here or during `qml.execute`. That would resolve the ordering of sum-> sprod -> prod.

**Comment by timmysilv** [comment]
I'll confess I don't know the details of `simplify` for the various arithmetic operators, but if it generally puts operators into a form that we like, then I am a big fan of that plan. In other words, if we are getting the expectation of any arithmetic operator (sum, prod, sprod) we should first simplify. I'd also propose we expose the union of those as something like `ArithmeticObsType` so it's clear what we're doing/why. But I think that can be done in a subsequent PR

**Comment by eddddddy** [comment]
I agree we should delay that to a separate PR. I suspect we'll also need to fix the analytic case as well, right?

**Pull request merged**
