### PR TITLE
Fix Attribute Error when accessing identifiers on partial dataset

### PR DESCRIPTION
**Pull request by brownj85**
**Context:**
Accessing `identifiers` on a dataset for which all identifier attributes are not downloaded results in an `AttributeError`:

```
>>> dset = qml.data.load(
    'qchem', 
    molname='H3', 
    basis='STO-3G', 
    bondlength='0.5', 
    attributes=['molname'])[0]
>>> dset.identifiers #AttributeError
```

**Description of the Change:**

`Dataset.identifiers` will only return identifiers that are available on the dataset. The above example now looks like:

```
>>> dset.identifiers
{'molname': 'H3'}
```

**Benefits:**
Removes unexpected and potentially confusing error.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by eddddddy — COMMENTED** [review]
Looks good from my side, though I really don't have any say in this.

**Comment by brownj85** [comment]
> In the old datasets, identifiers were implied by definition/construction. If we can't separate this shared definition, we should at least download all identifiers

Ok, fair point. I've made two changes: identifiers will always be downloaded, and identifiers are no longer listed as possible attributes in `load_interactive()`

**Comment by DSGuala** [comment]
> `identifiers` are _not_ `attributes`

I agree on this one. I don't think we should support things like `dset.basis` or `load('qchem', molname = 'H2', attributes=['basis'])`. But I do think it's useful to have `dset.identifiers`

**Review by timmysilv — COMMENTED** [review]
re: attributes vs. identifiers, `load` and `load_interactive` should align. I'm not suuuuper concerned about exposing something like `Dataset.basis`, but I wouldn't want someone to request `attributes=["basis"]` or something like that. I'd say just update `load` to expand the `params` to include default values in the dict, then reject any attributes requested that are also in `params`

**Comment by brownj85** [comment]
> re: attributes vs. identifiers, `load` and `load_interactive` should align. I'm not suuuuper concerned about exposing something like `Dataset.basis`, but I wouldn't want someone to request `attributes=["basis"]` or something like that. I'd say just update `load` to expand the `params` to include default values in the dict, then reject any attributes requested that are also in `params`

The the current behaviour is equivalent - the `molname` attribute will be downloaded anyway, regardless of whether we filter out the list. Unless you want to throw an error if they include a parameter in `attributes`?

**Comment by obliviateandsurrender** [comment]
Just to be sure, `qml.data.list_attributes(data_name="data")` shouldn't list the identifier or elements we define as identifiers. 
About the error - I think we should throw an error and show the list of `valid` attributes (same as above) that they can download.

**Review by DSGuala — APPROVED** [review]

**Review by obliviateandsurrender — APPROVED** [review]

**Review by timmysilv — APPROVED** [review]

**Comment by brownj85** [comment]
> Just to be sure, `qml.data.list_attributes(data_name="data")` shouldn't list the identifier or elements we define as identifiers. About the error - I think we should throw an error and show the list of `valid` attributes (same as above) that they can download.

Added this

**Pull request merged**
