### PR TITLE
Update names of `qml.capture` switches

### PR DESCRIPTION
**Pull request by dwierichs**
**Context:**
#5509 added a `qml.capture` module. It contains switches that enable and disable the capturing mechanism, and a status reporting function about whether the mechanism is currently enabled.

**Description of the Change:**
This PR changes the name of these switches/status functions
- `qml.capture.enable_plxpr` --> `qml.capture.enable`
- `qml.capture.disable_plxpr` --> `qml.capture.disable`
- `qml.capture.plxpr_enabled` --> `qml.capture.enabled`

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

[sc-61510]

### CODE REVIEW

**Review by trbromley — APPROVED** [review]
Thanks @dwierichs!

**Review by rmoyard — APPROVED** [review]
Thanks it looks good to me :+1:

**Comment by dime10** [comment]
If the third version is a query, would it make sense to name it `is_enabled`? (not sure if this follows existing pennylane conventions or not)

**Comment by albi3ro** [comment]
> If the third version is a query, would it make sense to name it `is_enabled`? (not sure if this follows existing pennylane conventions or not)

We don't really have conventions for this kinda of thing, so what ever we think works well enough.

**Pull request merged**
