### PR TITLE
[BugFix] Removing the Hermitian check in `qml.Hermitian`

### PR DESCRIPTION
**Pull request by PietropaoloFrisoni**
**Context:**   After some discussion, we decided to completely remove the 'Hermitianity' input validation check in the `qml.Hermitian` class since it might be expensive for very large matrices. Furthermore, it is used every time we call the `compute_matrix` and `compute_decomposition` methods.

Our current validation strategy is to raise errors if the corresponding error is rather difficult to debug and/ or the sanity check is sufficiently cheap and jittable.

In this case, the validation check is neither cheap nor jittable.  And the user might actually want to provide a non-hermitian matrix-based observable.

**Description of the Change:** As above.

**Benefits:** Faster execution and jittability.

**Possible Drawbacks:** The main drawback is that if the user provides by accident a non-Hermitian matrix to the `qml.Hermitian` class believing it is actually Hermitian, he/she might experience strange errors because the code doesn't check explicitly the input matrix anymore.

**Related GitHub Issues:** #6640 

**Related Shortcut Stories:** [sc-79122]

### CODE REVIEW

**Comment by CatalinaAlbornoz** [comment]
Thanks for working on this Pietro!
When this is merged can we test if this solves the original user question [here in the forum](https://discuss.pennylane.ai/t/trouble-compiling-circuits-with-qml-hermitian-using-jax-jit/7650)? 

I want to message the user letting them know when the fix is in.

**Comment by PietropaoloFrisoni** [comment]
Hi @CatalinaAlbornoz,

> I want to message the user letting them know when the fix is in.

Yes, apologies for the delay in merging this. We have high-priority epics to work on right now, but I hope we'll be able to allocate reviewers and merge this PR soon (hopefully before the end of the quarter).

> When this is merged can we test if this solves the original user question [here in the forum](https://discuss.pennylane.ai/t/trouble-compiling-circuits-with-qml-hermitian-using-jax-jit/7650)?

I tried with PennyLane installed from this branch and the example seems to work. I get the following output:
```
Result: Array([0.992445 , 0.9689125], dtype=float32)
```

So the example reported by the user should work with PennyLane installed from master once this is merged.
All the best!

**Comment by CatalinaAlbornoz** [comment]
Thanks @PietropaoloFrisoni ! The user confirmed that their problem is solved by using this branch. Thanks again for the fix!

**Review by albi3ro — APPROVED** [review]

**Review by andrijapau — APPROVED** [review]
LGTM! 😄

**Pull request merged**
