### PR TITLE
Pass keyword arguments of `MomentumQNGOptimizer` to base class; Fix `QNGOptimizer` update with singular metric tensor

### PR DESCRIPTION
**Pull request by astralcai**
**Context:**
The newly added `MomentumQNGOptimizer` in https://github.com/PennyLaneAI/pennylane/pull/6240 does not use the keyword arguments `approx` and `lam`. 

**Description of the Change:**
Pass the unused arguments to `super().__init__`

**Possible Drawbacks:**
No tests are added for this, but these two parameters are inherited from the base class, and they are never tested in the existing test module for the base class to begin with.

### CODE REVIEW

**Review by PietropaoloFrisoni — APPROVED** [review]
Thanks for the catch!

**Review by dwierichs — APPROVED** [review]
By now most of the changes were made by me, which makes the review a bit pointless. Maybe we can request one more review if desired.

**Comment by astralcai** [comment]
> By now most of the changes were made by me, which makes the review a bit pointless. Maybe we can request one more review if desired.

Thank you so much! @dwierichs

**Comment by JerryChen97** [comment]
I can take a look if it's more like a linalg related issue

**Comment by JerryChen97** [comment]
In [qml.optimize.qnspsa](https://github.com/PennyLaneAI/pennylane/blob/63742e53546f3b25b1f0c6b60841ff9e0b1cdba9/pennylane/optimize/qnspsa.py#L328-L331) there's a similar usage of `solve`. Not sure yet if it should be treated as well @dwierichs @astralcai

**Review by JerryChen97 — APPROVED** [review]
LGTM! I already committed the same correction in `momentum_qng` which is the only thing I saw that needs to add

**Pull request merged**
