### PR TITLE
Fix `qml.counts` measurement in new device

### PR DESCRIPTION
**Pull request by eddddddy**
**Context:**
Part of the effort to integrate the new device API. Most measurements are supported with only a few weird edge cases (including counts).

**Description of the Change:**
Previous behaviour:
```
>>> dev = DefaultQubit2()
>>> qs1 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(wires=[0, 1])], shots=15)
>>> dev.execute(qs1)
{'FalseFalse': 9, 'TrueFalse': 6}
>>> qs2 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(qml.PauliZ(0))], shots=15)
>>> dev.execute(qs2)
{tensor(-1, requires_grad=True): 10, tensor(1, requires_grad=True): 5}
```

New behaviour:
```
>>> dev = DefaultQubit2()
>>> qs1 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(wires=[0, 1])], shots=15)
>>> dev.execute(qs1)
{'00': 9, '10': 6}
>>> qs2 = qml.tape.QuantumScript([qml.RY(1.4, wires=0)], [qml.counts(qml.PauliZ(0))], shots=15)
>>> dev.execute(qs2)
{-1,: 10, 1: 5}
```

### CODE REVIEW

**Review by mudit2812 — APPROVED** [review]
Looks great. Thanks @eddddddy ! 🚀

**Review by albi3ro — COMMENTED** [review]
🎉 

Just changelog and unit tests for `CountsMP.process_samples`.

Actually not seeing any unit tests for `CountsMP.process_samples` in `test_counts.py`, but this might be a good opportunity to change that.  Even simple stuff like:
```
samples = np.zeros((4,2))
output = CountsMP(wires=(0,1)).process_samples(samples, wire_order=(0,1))
assert output == {'00': 4}
```
or something. probably messed up the orders, but you know what I mean anyway.

**Comment by eddddddy** [comment]
@albi3ro There are unit tests in `test_counts.py`, but those tests use integer arrays for the samples instead of boolean arrays. Isn't this behaviour new for `DefaultQubit2`? Should I change the previous unit tests to accept boolean arrays instead?

**Review by albi3ro — APPROVED** [review]
Thanks for the added tests. Looks great 🎉

**Comment by eddddddy** [comment]
[sc-38218]

**Pull request merged**
