### PR TITLE
Update measurements.py

### PR DESCRIPTION
**Pull request by JerryChen97**
**Context:**
revert the abstract deco for StateMeasurement.process_density_matrix to avoid unwanted conflicts for any downstreaming implementation.
**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related ShortCut Story:**
[sc-75238]

### CODE REVIEW

**Comment by astralcai** [comment]
You might want to go back to the tests and remove some of the ad-hoc implementations of `process_density_matrix` you added that always returns 1.

**Review by albi3ro — COMMENTED** [review]
We may also need to add `test_state_measurement_process_density_matrix_not_implemented` back it:

```
    def test_state_measurement_process_density_matrix_not_implemented(self):
         """Test that the process_density_matrix method of StateMeasurement raises
         NotImplementedError."""

         class MyMeasurement(StateMeasurement):
             def process_state(self, state, wire_order):
                 return qml.math.sum(state)

         with pytest.raises(NotImplementedError):
             MyMeasurement().process_density_matrix(
                 density_matrix=qml.math.array([[1, 0], [0, 0]]), wire_order=Wires([0, 1])
             )
```

**Review by astralcai — APPROVED** [review]

**Review by albi3ro — APPROVED** [review]
👍

**Comment by JerryChen97** [comment]
Somehow the codecov seems to be blocked and in waiting all the time so I couln't merge it @albi3ro

**Comment by albi3ro** [comment]
> Somehow the codecov seems to be blocked and in waiting all the time so I couln't merge it @albi3ro

rerunning the cancelled jax tests.

**Comment by JerryChen97** [comment]
Enabled Auto-Merge

**Pull request merged**
