### PR TITLE
Removing `semantic_version` from required packages

### PR DESCRIPTION
**Pull request by PietropaoloFrisoni**
**Context:** After #5769  and #5754, we can potentially replace all the occurrences of the `semantic_version` package with `packaging` in the PennyLane source code, and remove `semantic_version` from the required Python packages.

**Description of the Change:** As stated above, we replace the remaining occurrences of `semantic_version` with `packaging` and remove `semantic_version` from the required packages in PennyLane.

**Benefits:** One package less to keep track of in the dependencies.

**Possible Drawbacks:** None that I can think of, providing that there are no incompatibilities with the previous workflow (in which case, we can always revert this PR)

**Related GitHub Issues:** None.

**Related ShortCut Stories:** [sc-64659]

### CODE REVIEW

**Review by timmysilv — APPROVED** [review]
looks good!

**Review by mlxd — COMMENTED** [review]
Thanks @PietropaoloFrisoni 
Do we want to remove it from `docs/requirements.txt` also?

**Comment by PietropaoloFrisoni** [comment]
Thanks @mlxd, I forgot about that. Removed :+1:

**Review by mlxd — APPROVED** [review]
:100:

**Pull request merged**
