### PR TITLE
Support sum of `HardwareHamiltonian` and `int/float`.

### LINKED ISSUE #4310: [BUG] `sum` not working with hardware Hamiltonians (transmons and rydberg)
### Expected behavior

Working with hardware Hamiltonians, we add them together with similar syntax to `H = H_interaction + H_drive`. Often, we repeatedly add terms manually, e.g., `H_drive += qml.pulse.transmon_drive(amplitude, phase, freq, wires)`.

I would expect to be able to use `sum()` on a list of terms, such as:
`H_drive = sum([qml.pulse.transmon_drive(amplitude, phase, freq, q) for q in wires])`
Similar to how we can add other operators in PennyLane `sum([qml.PauliX(i) for i in range(wires)])`.

### Actual behavior

We can't do it.

### Additional information

I have tested this with a few `HardwareHamiltonian` instances using `qml.pulse.transmon_interaction`, `qml.pulse.transmon_drive`, `qml.pulse.rydberg_interaction` and `qml.pulse.rydberg_drive`.

We can manipulate all of them with stuff such as:
```python
H = qml.pulse.transmon_interaction(qubit_freqs, connection, couplings, wires)
for q in wires:
    H += qml.pulse.transmon_drive(amplitude, phase, freq, q)
```
Or even:
```python
H_int = qml.pulse.transmon_interaction(qubit_freqs, connection, couplings, wires)
drive_terms = [qml.pulse.transmon_drive(amplitude, phase, freq, q) for q in range(2)]
H_drive = drive_terms[0] + drive_terms[1]
H = H_int + H_drive
```

But we wouldn't be able to use `sum()` on any iterable containing `HardwareHamiltonian`s. I also tried changing the input types, e.g., setting `amplitude`, `phase`, and `freq` to be all callables, floats, or ints, or a combination of those.

### Source code

```shell
import pennylane as qml
sum([qml.pulse.transmon_drive(0., 0., 0., q) for q in range(2)])
```

### Tracebacks

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 2
      1 import pennylane as qml
----> 2 sum([qml.pulse.transmon_drive(0., 0., 0., q) for q in range(2)])

TypeError: unsupported operand type(s) for +: 'int' and 'HardwareHamiltonian'
```

### System information

```shell
Latest master

Name: PennyLane
Version: 0.32.0.dev0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/borja.requena/.conda/envs/pl_dev/lib/python3.10/site-packages
Editable project location: /home/borja.requena/GitHub/pennylane
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml
Required-by: PennyLane-Lightning

Platform info:           Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python version:          3.10.11
Numpy version:           1.23.5
Scipy version:           1.10.0
Installed devices:
- default.gaussian (PennyLane-0.32.0.dev0)
- default.mixed (PennyLane-0.32.0.dev0)
- default.qubit (PennyLane-0.32.0.dev0)
- default.qubit.autograd (PennyLane-0.32.0.dev0)
- default.qubit.jax (PennyLane-0.32.0.dev0)
- default.qubit.tf (PennyLane-0.32.0.dev0)
- default.qubit.torch (PennyLane-0.32.0.dev0)
- default.qutrit (PennyLane-0.32.0.dev0)
- null.qubit (PennyLane-0.32.0.dev0)
- lightning.qubit (PennyLane-Lightning-0.31.0)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

### PR DESCRIPTION
**Pull request by dwierichs**
**Context:**
The addition of `HardwareHamiltonian` instances needs to be implemented manually. This implementation currently does not support the addition between a `HardwareHamiltonian` and an `int` or a `float`. As a consequence, using the builtin `sum` on a sequence of `HardwareHamiltonian` instances is not supported.

**Description of the Change:**
This PR adds support for the addition between `HardwareHamiltonian` and `int/float`. As a consequence, the following now works:
```python
H = sum([qml.pulse.transmon_drive(0., qml.pulse.constant, 0., q) for q in range(2)])
```

**Benefits:**
Support more use cases and the use of the builtin `sum`.

**Possible Drawbacks:**
Performance: Executing a minimal QNode (see below) suffers by about 7%, which is too much in my opinion.
The overhead should become negligible for larger QNodes.

Some timings:
```python
import pennylane as qml

H1 = sum([qml.pulse.transmon_drive(0., qml.pulse.constant, 0., q) for q in range(2)])
H2 = qml.pulse.transmon_drive(0., qml.pulse.constant, 0., 0) + qml.pulse.transmon_drive(0., qml.pulse.constant, 0., 1)

%timeit qml.matrix(H1) # 2.19 ms ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit qml.matrix(H2) # 1.99 ms ± 27.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

dev = qml.device("default.qubit.jax", wires=2)

@qml.qnode(dev, interface="jax")
def node1(params):
    qml.evolve(H1)(params, 0.3)
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1))

@qml.qnode(dev, interface="jax")
def node2(params):
    qml.evolve(H2)(params, 0.3)
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1))

params = jnp.array([0.4, -0.9])
%timeit node1(params) # 366 ms ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit node2(params) # 344 ms ± 7.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Related GitHub Issues:**
fixes #4310

### CODE REVIEW

**Comment by dwierichs** [comment]
There was a mistake in timing the `qml.matrix` evaluation: I did not pass parameters to that call, so that it did not really compute the matrices. I updated the times.

**Comment by dwierichs** [comment]
After rerunning timings with different methods (`timeit`, custom timer using `time.process_time`), I come to the conclusion that the fluctuations in the timings are too large to judge the impact of this PR properly :/

**Comment by BorjaRequena** [comment]
Nice! Then it is just as we expected with the constant term overhead only being noticeable for very small systems 😄 Also, it is only when we use `sum` or explicitly add a constant term so, if our goal was performance, we could always avoid this construction.

We could check if `other == 0` and return self to remove the term coming from `sum` (if it does not break jitability), as we discussed offline.

**Comment by dwierichs** [comment]
>We could check if other == 0 and return self to remove the term coming from sum (if it does not break jitability), as we discussed offline.

This actually seems to work fine, because the implementation is in particular for `int` and `float`, so that tracers are not "accidentally" supported anyways. :) 

I added tests.

**Review by BorjaRequena — APPROVED** [review]
Looks good! 🚀 

I pushed a couple of edits to please pylint and I believe it's good to go. I am not sure I understand why we do not want the additional identity to be queued, but we can discuss this offline 😄

**Review by Qottmann — APPROVED** [review]
Thanks @dwierichs looks good to me 👍

**Review by trbromley — COMMENTED** [review]
Thanks @dwierichs! To confirm, could users still do a `sum`-like operation without the slowdown by doing:
```python
terms = [qml.pulse.transmon_drive(0., qml.pulse.constant, 0., q) for q in range(2)]
sum(terms[1:], start=terms[0])
```

**Comment by dwierichs** [comment]
Yep, this is equivalent to manually initializing the first term and then adding the others, so it never hits the newly added logic :)

**Pull request merged**
