### PR TITLE
fix fourier docs to use circuit_spectrum

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
`qml.fourier.spectrum` was deprecated and replaced with `circuit_spectrum` in #1681

**Description of the Change:**
Update the qml_fourier doc to match the latest code

**Benefits:**
Docs are more up-to-date as a whole

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
N/A

### CODE REVIEW

**Review by Jaybsoni — APPROVED** [review]
Looks good, thanks for fixing this asap! Were you able to run this new version and obtain the same results?

**Comment by eddddddy** [comment]
Also line 137 needs to be changed 🙂

**Comment by Jaybsoni** [comment]
> Also line 137 needs to be changed 🙂

And 106 😄

**Comment by timmysilv** [comment]
lol ty all. confirmed that the code snippet here works

**Review by eddddddy — APPROVED** [review]

**Pull request merged**
