### PR TITLE
Improve consistency in treatment of optimizer hyperparameters

### PR DESCRIPTION
**Pull request by AkashNarayanan**
**Context:**
The hyperparameter for `GradientDescentOptimizer` is a private variable whereas the hyperparameters for all the other optimizers are public variables. This PR makes the `_stepsize` hyperparameter public and adds a temporary backward compatibility to support the use of `_stepsize`.

**Description of the Change:**
* `_stepsize` has been made a public variable `stepsize`
* `UserWarning` has been added to the `update_stepsize` method with a deprecation message.
* To support backward compatibility temporarily, a property `_stepsize` has been added to get and set `stepsize`. `UserWarning` has been added to the property with a deprecation message.
* `test_update_stepsize` has been updated to check if a `UserWarning` is raised the method is used.
* A test case has been added to check if it is possible to get and set `stepsize` using the `_stepsize` property and whether a `UserWarning` is raised while doing so.

**Related GitHub Issues:**
#1578

### CODE REVIEW

**Comment by AkashNarayanan** [comment]
Hi @albi3ro ! Can you please help me with the formatting check? When I run black locally, around 109 files get reformatted! I tried running pylint on `shot_adaptive.py` and got the following output.
```
************* Module shot_adaptive
shot_adaptive.py:22:0: E0402: Attempted relative import beyond top-level package (relative-beyond-top-level)
shot_adaptive.py:229:21: E1101: Module 'pennylane.numpy' has no 'abs' member (no-member)
shot_adaptive.py:229:38: E1101: Module 'pennylane.numpy' has no 'sum' member (no-member)
shot_adaptive.py:229:45: E1101: Module 'pennylane.numpy' has no 'abs' member (no-member)
shot_adaptive.py:252:24: E1101: Module 'pennylane.numpy' has no 'expand_dims' member (no-member)
shot_adaptive.py:289:25: E1101: Module 'pennylane.numpy' has no 'sum' member (no-member)
shot_adaptive.py:289:32: E1101: Module 'pennylane.numpy' has no 'abs' member (no-member)
shot_adaptive.py:382:20: E1101: Module 'pennylane.numpy' has no 'ndindex' member (no-member)
shot_adaptive.py:384:16: E1101: Module 'pennylane.numpy' has no 'zeros_like' member (no-member)
shot_adaptive.py:385:16: E1101: Module 'pennylane.numpy' has no 'zeros_like' member (no-member)
shot_adaptive.py:389:25: E1101: Module 'pennylane.numpy' has no 'mean' member (no-member)
shot_adaptive.py:390:25: E1101: Module 'pennylane.numpy' has no 'var' member (no-member)
shot_adaptive.py:419:16: E1101: Module 'pennylane.numpy' has no 'zeros_like' member (no-member)
shot_adaptive.py:419:39: E1101: Module 'pennylane.numpy' has no 'int64' member (no-member)
shot_adaptive.py:427:34: E1101: Module 'pennylane.numpy' has no 'sum' member (no-member)
shot_adaptive.py:436:24: E1101: Module 'pennylane.numpy' has no 'zeros_like' member (no-member)
shot_adaptive.py:436:47: E1101: Module 'pennylane.numpy' has no 'float64' member (no-member)
shot_adaptive.py:437:23: E1101: Module 'pennylane.numpy' has no 'zeros_like' member (no-member)
shot_adaptive.py:437:46: E1101: Module 'pennylane.numpy' has no 'float64' member (no-member)
shot_adaptive.py:451:16: E1101: Module 'pennylane.numpy' has no 'ceil' member (no-member)
shot_adaptive.py:467:27: E1101: Module 'pennylane.numpy' has no 'unravel_index' member (no-member)
shot_adaptive.py:467:44: E1101: Module 'pennylane.numpy' has no 'argmax' member (no-member)
shot_adaptive.py:469:26: E1101: Module 'pennylane.numpy' has no 'squeeze' member (no-member)
shot_adaptive.py:469:37: E1101: Module 'pennylane.numpy' has no 'int64' member (no-member)
shot_adaptive.py:469:46: E1101: Module 'pennylane.numpy' has no 'clip' member (no-member)

------------------------------------------------------------------
Your code has been rated at 0.74/10 (previous run: 0.74/10, +0.00)
```

**Comment by AkashNarayanan** [comment]
At the moment `test_optimize_shot_adaptive.py` is in the `tests` folder. Can we move it to the `optimize` folder within the `tests` folder and rename it to `test_shot_adaptive.py`?

**Comment by dwierichs** [comment]
The reason for `test_optimize_shot_adaptive.py` not being in the `optimize` subdirectory is, that the tests for the [PR that introduced the subdirectory](https://github.com/PennyLaneAI/pennylane/pull/1489) were failing when we moved it to there. If you manage to have the tests succeed while moving the test file, that would be great! (It might just work immediately, we suspected that this was a cross merge issue.)

**Comment by AkashNarayanan** [comment]
Hi @dwierichs ! I moved the test file to the `optimize` subdirectory and renamed it `test_shot_adaptive.py`. There are no additional failing test cases and the code coverage remains the same but there are two less warnings. I am not sure why that is so. Is it bad that there are two less warnings?

Regarding the black formatting, when I try to run `black -l 100 pennylane tests` from the PennyLane root folder, around 109 files get reformatted. So I just ran it on the `test_optimize.py` file (36540f24f291fd3b07854c8553c30be1c497827f) but the formatting check failed. Running black again did not make any change. I ran pylint on the file and found that there were two lines over 100 characters long. So I adjusted the line length (a7eea6dab5ba9c2ce5961cfba6953383a95dae20) but the formatting check still fails.

**Comment by AkashNarayanan** [comment]
The formatting check finally passed! :tada: 
I had to adjust the line length and remove some trailing white spaces in `test_optimize.py`. I wonder why `black` didn't fix it already.

**Comment by dwierichs** [comment]
Hi @AkashNarayanan, which warnings vanished when you moved the test file? Sounds like this indeed was a cross merge problem earlier and in fact works perfectly fine.
Thanks for taking care of this :)

**Comment by AkashNarayanan** [comment]
I tried comparing the output files of tests performed before and after moving the file. The following two lines are missing after moving the file.
```
tests/test_optimize_shot_adaptive.py::TestSingleShotGradientIntegration::test_single_array_argument_step[cost_fn1]
tests/test_optimize_shot_adaptive.py::TestSingleShotGradientIntegration::test_multiple_array_argument_step
```
I am not sure if they refer to warnings. I do not see any code to catch warnings within the `test_single_array_argument_step` and `test_multiple_array_argument_step` methods.

**Comment by dwierichs** [comment]
Yes, those lines appearing together with others means that they also raised the given warning (they are caught by pytest, btw :) )
The "problem" here is that the tests for the shot adaptive optimizer rely on randomly sampled shots and do not fix the seed, so that the division-by-zero error that is being reported only occurs sometimes. 
This should not be of concern here, however, and at most would be a good new issue, imho ;-)

**Comment by AkashNarayanan** [comment]
Oh, that's interesting. I have been learning something new with each of the issue I have tried to solve so far. This is fun!

**Review by albi3ro — APPROVED** [review]
Thanks @AkashNarayanan .  I made a suggestion for the changelog, but I'm going to go ahead and approve.

I have since learned we didn't need to worry about a deprecation cycle for `_stepsize`, because anyone using a private variable accepts the risks of it changing on them, but no harm in having it I say.

Thanks for the PR 🎉 

I'm just going to commit the comment and merge this into master.

**Pull request merged**
