### PR TITLE
Add examples to few operations

### PR DESCRIPTION
**Pull request by ankit27kh**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**
 Add examples that show how to create and use the following operations:
PauliRot
QubitUnitary
QubitStateVector
BasisState
**Description of the Change:**
Added examples to the 4 operations
**Benefits:**
Examples for the mentioned operations
**Possible Drawbacks:**
N/A
**Related GitHub Issues:**
#1727

### CODE REVIEW

**Comment by ankit27kh** [comment]
#1727 also requires examples for templates. That is also connected with #1735. A separate PR for these will be best.

**Comment by antalszava** [comment]
Hi @ankit27kh thank you for this submission! :slightly_smiling_face:  Should we go for a review on it?

**Comment by ankit27kh** [comment]
@antalszava yes I think this is ready.

**Review by antalszava — CHANGES_REQUESTED** [review]
@ankit27kh this looks great, so helpful to have in! :heart_eyes: The only change requested would be to add an item to the `Documentation` section of the changelog file (`doc/releases/changelog-dev.md`) and to add yourself to the list of contributors. :slightly_smiling_face:

**Comment by ankit27kh** [comment]
@antalszava done!

**Review by antalszava — APPROVED** [review]
Thank you! :heart_eyes:

**Pull request merged**
