### PR TITLE
[WIP] Add FockDiagonalObservable

### PR DESCRIPTION
**Pull request by antalszava**
**Context**

Adds the `FockDiagonalObservable` as per #951.

### CODE REVIEW

**Comment by antalszava** [comment]
[ch1061]

**Comment by josh146** [comment]
@antalszava just checking the status of this PR :)

**Comment by antalszava** [comment]
Thanks for checking in! It's very much a work in progress PR at the moment. If preferred, could close this and re-open once picked up again.

**Comment by josh146** [comment]
@antalszava should we close this PR? I realize it might be quite out of date!

**Comment by antalszava** [comment]
Yes, closing this. We can reopen if need be.

**Pull request closed without merging**
