### PR TITLE
RTD build fails on warnings, remove extra github action

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
Noted by @rashidnhm [here](https://github.com/PennyLaneAI/pennylane/pull/4754#discussion_r1473444720). We have the "Documentation Check" action to ensure that there are no warnings being raised by sphinx, but the docs build itself can handle that!

**Description of the Change:**
- Update the RTD build to fail on warning
- Remove the CI workflow that checks for warnings in docs builds

**Benefits:**
- One less worker on every PR
- One less file to maintain

**Possible Drawbacks:**
We will no longer get the annotations on files that indicate where the warning comes from. It's a notable drawback, so I invite any conversation around it!

**Related GitHub Issues:**
Might cause less pain in #4754

### CODE REVIEW

**Comment by josh146** [comment]
> We will no longer get the annotations on files that indicate where the warning comes from. It's a notable drawback, so I invite any conversation around it!

If this is useful for the team/for external contributors, this is perhaps an argument to keep the existing docs check -- will leave it up to the team.

**Review by rashidnhm — COMMENTED** [review]
Great stuff @timmysilv ! I am wondering .. is there a way we could make a temp docs change (within this PR) that would raise a sphinx warning so we ensure that RTD build would fail as expected?

As for not getting annotations on the file itself, that is indeed something useful we are losing. But we can still see which lines are raising the warnings by looking at the RTD build (which I believe are public).

**Comment by josh146** [comment]
> As for not getting annotations on the file itself, that is indeed something useful we are losing. But we can still see which lines are raising the warnings by looking at the RTD build (which I believe are public).

@rashidnhm yep for sure. It just would be less visible to external contributors if that's a tradeoff we're happy with.

There is one other benefit I can think of to keeping the two actions: sometimes, viewing a (badly rendered) RTDs build can help troubleshoot the failing Sphinx warnings, because the sphinx warnings can be not very verbose.

**Comment by timmysilv** [comment]
i hijacked the "Documentation Check" action to generate `pip freeze` results because the official RTD build doesn't have permission to push commits to the repo

**Pull request closed without merging**
