### PR TITLE
Add `SProd.terms()` method

### PR DESCRIPTION
**Pull request by Qottmann**
Missed to add `SProd.terms()`, `SProd.ops` and `SProd.coeffs`, fixing this here

### CODE REVIEW

**Review by PietropaoloFrisoni — APPROVED** [review]
Great. Thank you for adding this!

**Review by albi3ro — APPROVED** [review]

**Comment by dime10** [comment]
@Qottmann could you elaborate what the intention here is? Is it that `SProd` should recursively determine what the terms and coeffs are? Only one level deep or several? Only for specific observables or all?

I believe previously it always returned a single coeff (the scalar) and a single observable (whether compound or not), but happy to be corrected here.

**Comment by Qottmann** [comment]
In `Prod` and `Sum` the `terms()` method flattens out the operator to its coefficients and "pure" and simplified ops (i.e. products are executed). The request was for that to be consistens also with `SProd` such that you always receive a flattened down list of coeffs and ops.

E.g. if you have some operator `op = qml.sum(*[qml.s_prod(0.5, X(i)) for i in range(3)])`. The terms are `[0.5, 0.5, 0.5]` and `[X(i) for i in range(3)]`. Consider that you then later decide to renormalize it by multiplying with a scalar `op = 2 * op`, but now the terms would just yield `[2]`, [<original_op]`. The motivation was for this to be consistent.

Frankly its not super urgent and probably a matter of taste what one prefers.

**Comment by dime10** [comment]
Thanks @Qottmann! The change is not a problem for us as long as we're aware of the new behaviour, so feel free to re-mere this whenever convenient :)

**Comment by dime10** [comment]
Was this added back or is that not planed anymore?

**Comment by albi3ro** [comment]
@dime10 Still definitely wanted, but I guess is got backlogged.  Probably too late for the next release, but we should definitely look into making this change together in tandem.

**Comment by dime10** [comment]
Just checking in on this again 😅

**Comment by albi3ro** [comment]
@astralcai is now looking into this again with #5885 . But not going into the release since we know it's going to break things for catalyst.

**Pull request merged**
