### PR TITLE
[Code together] Creating a qft.py file in the subroutines folder

### PR DESCRIPTION
**Pull request by anonymousr007**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `.github/CHANGELOG.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by rmoyard** [comment]
Hey @anonymousr007, thank you for the contribution! Pls edit your post and use the submit form it gives you information about requirements for testing, code coverage and linting. Let me know if you have any questions about this process.

**Comment by anonymousr007** [comment]
> Hey @anonymousr007, thank you for the contribution! Pls edit your post and use the submit form it gives you information about requirements for testing, code coverage and linting. Let me know if you have any questions about this process.

**Comment by rmoyard** [comment]
You don't need to close the PR, you can use the edit button on your post :)

**Comment by rmoyard** [comment]
@anonymousr007 I edited your post then you have all information 👍

**Comment by anonymousr007** [comment]
So,I created a `test_qft` file in `test_subroutines` folder

**Comment by rmoyard** [comment]
@anonymousr007 Perfect that's a good start! You should move the tests for QFT there. Then you should run them and check if everything is passing `make test`. Don't forget to add your name in the contribution list in the `CHANGELOd.md` file. You should also pip install `pylint` and use it on the files you created. You can also install `black` and run it like that `black -l 100 pennylane/path/to/modified/file.py`. Finally push your results on this PR 💯

**Comment by antalszava** [comment]
Hi @anonymousr007, could it be that you have to upgrade the `black` version you're using with `pip install --upgrade black`?

**Comment by anonymousr007** [comment]
Hi @antalszava , Please review this pull request [#1558](https://github.com/PennyLaneAI/pennylane/pull/1558)

**Pull request closed without merging**
