### PR TITLE
Remove dtype promotion in pauli rep of scalar products with tensorflow

### PR DESCRIPTION
**Pull request by Qottmann**
fix for https://github.com/PennyLaneAI/pennylane/issues/5245 

[sc-57300]

### CODE REVIEW

**Review by astralcai — APPROVED** [review]
Looks good! 🎸

**Comment by timmysilv** [comment]
@Jaybsoni do you remember why this was added in the first place? You first made a change [here](https://github.com/PennyLaneAI/pennylane/pull/3481/files#diff-671e95c6e7872137547782b3189f4885dee3e514b55f2abe6b7728d2c7fd9891R144-R145), then I had some issue so I just explicitly set it to complex128. if there's no hidden issue with this removal, then lgtm! just wanna make sure with the experts here.

**Comment by albi3ro** [comment]
I also thought this was done deliberately to fix errors rising due to tensorflow conversion issues.  But tests seem to be passing so I guess we're ok?

**Comment by Qottmann** [comment]
Can I merge to master right now or should I wait for decoupling the release candidate branch?

**Pull request merged**
