### PR TITLE
`Controlled` subclasses no longer bind base class primitives on initialization

### PR DESCRIPTION
**Pull request by mudit2812**
The constructors of subclasses of `Controlled` (`CNOT`, `CRX`, etc.) construct the base operator so that the parent `Controlled` class can be initialized correctly. However, in doing so, the primitive of the base operator is also binded. We don't want this, because calling constructors is part of the concrete implementation, and binding primitives can create abstract values (when using `make_jaxpr`, etc.), which we don't want.

Changes:
* Update all currently existing subclasses of `Controlled` to use `type.__call__(base_op_class, ...)` instead of `base_op_class(...)` to construct the base operator. This skips the call to `op._primitive.bind` and just directly creates the class we want to construct.

Downsides:
* This will need to be done for all subclasses of `Controlled`, so it is an additional detail that devs have to keep in mind when adding new controlled ops.

[sc-79769]

### CODE REVIEW

**Review by albi3ro — COMMENTED** [review]
Do we have time to write some tests?

One way to test if this works if to do:

```
@DefaultQubitInterpreter(num_wires=3)
def f():
    qml.CNOT((0,1))
    return qml.state()

jax.jit(f)()
```
or something like that.

**Comment by mudit2812** [comment]
@albi3ro Thanks for the suggestion. I was stuck on what tests should be added 😄 . I'd like to localize the test further, so I'm going to add a test that uses `PlxprInterpreter` instead of `DefaultQubitInterpreter`, and `jax.make_jaxpr` instead of `jax.jit`.

**Comment by albi3ro** [comment]
> @albi3ro Thanks for the suggestion. I was stuck on what tests should be added 😄 . I'd like to localize the tests further, so I'm going to add a test that uses `PlxprInterpreter` instead of `DefaultQubitInterpreter`, and `jax.make_jaxpr` instead of `jax.jit`.

Even something like:
```
@qml.capture.PlxprInterpreter()
def f():
    qml.CNOT((0,1))
    qml.RX(0.1, (0,1))
    qml.Toffoli((0,1,2))

jax.make_jaxpr(f)()
```

**Comment by lillian542** [comment]
I ask this without detailed information about the PlxprInterpreter - would there be a way to have a version of the test in `assert_valid` and check that the base isn't being bound for all Controlled operations? 

No worries if that's tricky to do, just wondering if we can add an easy check to make sure we remember to do this with future operations.

**Comment by albi3ro** [comment]
> I ask this without detailed information about the PlxprInterpreter - would there be a way to have a version of the test in `assert_valid` and check that the base isn't being bound for all Controlled operations?
> 
> No worries if that's tricky to do, just wondering if we can add an easy check to make sure we remember to do this with future operations.

Maybe:
```
def _validate(op):
      qml.capture.enable()
      try:
            @qml.capture.PlxprInterpreter()
            def f():
                op._unflatten(*op._flatten())
                
            jax.make_jaxpr(f)()
    finally:
        qml.capture.disable()
```

**Comment by mudit2812** [comment]
@albi3ro @lillian542 mind if we make the `assert_valid` addition a backlog story and tackle it there?

**Comment by albi3ro** [comment]
> @albi3ro @lillian542 mind if we make the `assert_valid` addition a backlog story and tackle it there?

I could actually add this in #6343 in the `convert_to_tape` jaxpr-> tape function.

**Review by lillian542 — APPROVED** [review]
LGTM then!

**Review by albi3ro — APPROVED** [review]

**Pull request merged**
