### PR TITLE
default_qubit to use the hard-coded inverses

### LINKED ISSUE #870: Inverses in default_qubit
Several operations have hard coded implementations instead of simply using their unitary matrix.  These are specified at [default_qubit.py Line 130](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L130) such as `"PauliX"` or `"CNOT"`.  

These hard-coded functions like  [`dev._apply_phase`](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L328) can take in a boolean for the keyword `inverse` and apply the inverse operation instead.

**BUT** [`dev._apply_operation`](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L163) always sends inverse operations to the more general path using `dev._get_unitary_matrix` followed by something like `dev._apply_unitary`.

This happens because inverse operations have `.inv` appended to their name.  Thus the new name is no longer in the `dev._apply_ops` dictionary.

This can easily be fixed by changing `operation.name` to `operation.base_name` at [Line 179](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L179) and [Line 181](https://github.com/PennyLaneAI/pennylane/blob/9bbf560e830f951eaa421c2de20549b9d9e7af6c/pennylane/devices/default_qubit.py#L181)

### PR DESCRIPTION
**Pull request by albi3ro**
Closes #870

This pull request does not change any functionality.  It just makes the inverses of the common simple gates more efficient in `default.qubit` .  The functions were already there; now they actually get used.

### CODE REVIEW

**Review by trbromley — APPROVED** [review]
:100:

**Review by antalszava — APPROVED** [review]
Looks good to me! Thank you for catching this :slightly_smiling_face:

**Comment by josh146** [comment]
Thanks @albi3ro, this looks good for merging. One small request before it's merged in - could you add a small sentence and a link to this PR in the changelog, under either the 'Improvements' or 'Bug fixes' section (whichever one feels more relevant, I'm a bit on the fence).

**Comment by trbromley** [comment]
> under either the 'Improvements' or 'Bug fixes' section

I vote bug fix, since the code was expected to implement inverses using the special functions, but it wasn't due to a misunderstanding rather than by design.

**Comment by trbromley** [comment]
Updated the changelog: 14e8a5d0afda5eb05df5be142b1f2949c26c6022

**Pull request merged**
