### PR TITLE
Explicitly convert `prob` interface in `ProbsMP.process_density_matrix`

### PR DESCRIPTION
**Pull request by JerryChen97**
**Context:**
Previous `ProbsMP.process_density_matrix` has potential to alter the interface. Here we convert it explicitly.

Specifically, when dealing with batched density matrices, the previous `ProbabilityMP` did not track the interface of input `density_matrix`.

```python
import numpy as np
import pennylane as qml
from pennylane.measurements import ProbabilityMP as OriginalProbabilityMP
from pennylane.typing import TensorLike
from pennylane.wires import Wires

class CustomProbabilityMP(OriginalProbabilityMP):
    """Custom ProbabilityMP overriding process_density_matrix."""

    def process_density_matrix(self, density_matrix: TensorLike, wire_order: Wires):
        if len(np.shape(density_matrix)) == 2:
            prob = qml.math.diagonal(density_matrix)
        else:
            prob = qml.math.array(
                [qml.math.diagonal(density_matrix[i]) for i in range(np.shape(density_matrix)[0])]
            )

        # Commented out convert_like to simulate behavior without it.
        # prob = qml.math.convert_like(prob, density_matrix) 

        # Creating a pseudo-state using the diagonal probabilities
        p_state = qml.math.sqrt(prob)
        return self.process_state(p_state, wire_order)


# Instantiate the custom ProbabilityMP class
custom_prob_mp = CustomProbabilityMP()

# Define a density matrix as a NumPy array
density_matrix = qml.math.array(np.array([[[0.5, 0.5], [0.5, 0.5]], [[0.5, 0.5], [0.5, 0.5]], ]), like='torch')

# Define the wire order
wire_order = Wires([0, 1])

# Attempt to call process_density_matrix without convert_like
result = custom_prob_mp.process_density_matrix(density_matrix, wire_order)
print("Result without convert_like:", result)
# Result without convert_like: [[0.5 0.5]
# [0.5 0.5]]
```

With the fixed `ProbabilityMP` we have
```python
# Instantiate the custom ProbabilityMP class with convert_like uncommented
new_prob_mp = OriginalProbabilityMP()

# Use qml.math.convert_like internally to ensure compatibility
result = new_prob_mp.process_density_matrix(density_matrix, wire_order)
print("Result with convert_like:", result)
# Result with convert_like: tensor([[0.5000, 0.5000],
#        [0.5000, 0.5000]], dtype=torch.float64)
```

**Description of the Change:**
Enforce the probs to match input interface via `qml.math.convert_like`

**Benefits:**
This PR is blocking https://github.com/PennyLaneAI/pennylane/pull/6684. Its merge into master will free new `default.mixed` from many roundabout solutions.

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by PietropaoloFrisoni — APPROVED** [review]
Thanks @JerryChen97.

I just have one question: why create a single 1-line PR for this instead of applying the change directly in #6737?

**Comment by andrijapau** [comment]
We should probably add a test to ensure desired behaviour (interface remaining the same)?

**Comment by JerryChen97** [comment]
> Thanks @JerryChen97.
> 
> I just have one question: why create a single 1-line PR for this instead of applying the change directly in #6684 ?

The modification to ProbsMP is of different scope from #6684. 
I made same modification there but I dont expect it to merge within 2weeks.
However, ProbsMP as its own can be used in any ways allowed now, which contain this same bug and we should fix it sasp

**Comment by PietropaoloFrisoni** [comment]
@JerryChen97 Thanks. Then I would say that a test and possibly a changelog entry would be ideal here :+1:

**Comment by JerryChen97** [comment]
> ```python
> result = custom_prob_mp.process_density_matrix(density_matrix, wire_order)
> ```

Added interface assert for all the current 4 different testing branches

**Review by andrijapau — APPROVED** [review]
Nice, thanks for adding the tests 🎉

**Pull request merged**
