### PR TITLE
Fix the order of arguments to the `GaussianState` operation

### PR DESCRIPTION
**Pull request by antalszava**
**Context:**
PennyLane considers the arguments to the `GaussianState` operation in a different order than Strawberry Fields.

**Description of the Change:**
Changes the documented order of the arguments to the `GaussianState` operation.

**Benefits:**
The documentation corresponds to the order in which parameters are passed in the PennyLane-SF plugin. The `default.gaussian` device is also adjusted accordingly.

**Possible Drawbacks:**
Out of scope for this PR, internally the `default.gaussian` device still continues to use a different covariance matrix and vector of means ordering than Strawberry Fields.

Opened an issue to tackle this: https://github.com/PennyLaneAI/pennylane/issues/1257

**Related GitHub Issues:**
https://github.com/PennyLaneAI/pennylane-sf/issues/67

### CODE REVIEW

**Review by thisac — APPROVED** [review]
Thanks for working on this @antalszava! Would it perhaps be nice to add an integration test using the fock device as well here (testing the exact case as the one in the issue)? Couldn't really see anywhere where this was tested, i.e. that would have caught the issue in the first place.

**Comment by glassnotes** [comment]
> Thanks for working on this @antalszava! Would it perhaps be nice to add an integration test using the fock device as well here (testing the exact case as the one in the issue)? Couldn't really see anywhere where this was tested, i.e. that would have caught the issue in the first place.

@antalszava same comment about testing the `fock` device; when I tested it with the `default.gaussian` device things had run without issue. Unless, are the device-specific tests something that live in PennyLane-SF instead?

**Comment by antalszava** [comment]
@thisac @glassnotes thanks for the comments!

Yes, all testing is done in PennyLane-SF. If we were to add a test case here, we'd need PennyLane-SF to be a dependency of PennyLane. I can add a test there.

PennyLane core has the difference in storing & using the covariance matrices and vector of means from Strawberry Fields, that should be the reason for why it worked well with `default.gaussian`.

**Comment by antalszava** [comment]
The following test case in PennyLane-SF should cover our use case:
https://github.com/PennyLaneAI/pennylane-sf/blob/831131dbbe3b2e646a147522ea7f422137d03f71/tests/test_fock.py#L193

It has the correct order for gate parameters.

**Pull request merged**
