### PR TITLE
Pin pyscf<1.7.4 to allow scipy>=1.5 in QChem

### PR DESCRIPTION
**Pull request by antalszava**
**Context:**
The latest version of `pyscf` needs to pin `scipy<1.5` (as per #814). This can cause problems, however, when `scipy>=1.5` is required in environments or other packages depend on such versions.

**Description of the Change:**
Ping `pyscf<1.7.4` such that `scipy>=1.5` can be used in QChem.

**Benefits:**
`scipy>=1.5` can be used in QChem.

**Possible Drawbacks:**
The newest features of `pyscf` are not available.

**Related GitHub Issues:**
N/A

### CODE REVIEW

**Comment by josh146** [comment]
Thanks @antalszava! It might be a good idea to test building the QML repo with this branch 🙂 You could do that as follows:

* Checkout the `qml` repo, `dev` branch

* Create a new branch from `dev`, but modify `requirements.txt` so that (a) PennyLane and QChem and installed from _this_ branch, and (b) the pyscf/scipy versions match.

* In `.circleci/config.yml`, increase both the pip cache version and the demo cache version. This ensures that all requirements are re-installed, and that all tutorials are re-built.

* Push, and 🤞 that the CI passes in about 1.5 hours!

**Comment by antalszava** [comment]
Thanks @josh146! Created https://github.com/PennyLaneAI/qml/pull/166 (can delete if needed). We seem to have been pinning `pyscf==1.7.1` actually :thinking:  (https://github.com/PennyLaneAI/qml/blob/f6bcce1eada92589724c2584742f7aaa5c2f4334/requirements.txt#L13).

**Comment by antalszava** [comment]
The `qml` repo build was fine (with the exception of `tutorial_vqe_parallel`), link to the build and docs:
* https://app.circleci.com/pipelines/github/PennyLaneAI/qml/1938/workflows/2c1373f7-8e6a-48c7-9fba-d604a600e574/jobs/2008
* https://2008-214003948-gh.circle-artifacts.com/0/_build/html/index.html

**Review by josh146 — APPROVED** [review]

**Comment by josh146** [comment]
🤔

**Pull request merged**
