### PR TITLE
Undeprecate `ApproxTimeEvolution`

### PR DESCRIPTION
**Pull request by rmoyard**
**Description of the Change:**

`qml.evolve` is not at feature parity with `ApproxTimeEvolution` and should not have been replaced (Two demos are failing)

### CODE REVIEW

**Comment by timmysilv** [comment]
there's a bit more that needs changing. Can we just revert #3755 instead? If only specific files, you can do `git checkout 841932c56a1b2c10ae5798ba6963665893950794 list_of_files` (it's the parent commit from before that PR was merged)

**Comment by mudit2812** [comment]
Albert pushed a fix in #3796 that I think we should try before reverting the deprecation.

**Comment by rmoyard** [comment]
Deprecation kept but remove the replacement of ApproxTimeEvolution

**Comment by timmysilv** [comment]
I'm not sure how I feel about keeping it in some files while also deprecating it. It seems essentially like deprecating some functionality from all of those things (QAOA layers, commuting evolution, etc.) which I don't think we should do

**Comment by josh146** [comment]
If we keep the deprecation but retain its use, would users get a deprecation warning from using e.g., `qml.qaoa.mixer_layer`, that they wouldn't be able to act on?

In general, deprecation warnings should be a 'call to action' to users to update their code. But if they _can't_ update their code to remove use of this function, it does not feel like a deprecation.

**Comment by rmoyard** [comment]
I totally re added `ApporxTimeEvolution`.

**Review by timmysilv — APPROVED** [review]
at least for this release, lgtm!

**Review by trbromley — APPROVED** [review]
Thanks @rmoyard!

**Pull request merged**
