### PR TITLE
Fix allclose() test in test_qnn_torch

### PR DESCRIPTION
**Pull request by trbromley**
This test is causing CI tests to fail in https://github.com/XanaduAI/pennylane/pull/711. Upon investigation, it appears that the two values compared in `allclose()` have a small numerical discrepancy, causing the tests to fail. The solution is simply to add a tolerance to `allclose()`.

### CODE REVIEW

**Comment by co9olguy** [comment]
Please put any "magic numbers" like tolerances at the top of the file in ALL_CAPS

**Comment by co9olguy** [comment]
@trbromley what caused the tests to fail when they weren't failing before?

**Comment by co9olguy** [comment]
Also 1e-4 doesn't feel like a "machine-precision" error. Are we sure the functions aren't different because of a (small) bug, rather than a tolerance issue? Is there any truncation/approximation/estimation happening anywhere that might account for this?

**Comment by trbromley** [comment]
It appears to be https://github.com/XanaduAI/pennylane/pull/707 that introduced the occasional failure.

The test creates a `torch`-interface QNode and then inside `TorchLayer` tries to again convert this QNode to using the `torch` interface.

Note that https://github.com/XanaduAI/pennylane/pull/707 was done exactly for this scenario: converting QNodes that already have an interface.

**Comment by trbromley** [comment]
This is a comparison of the discrepancies for the failing tests:

image

**Comment by trbromley** [comment]
The change from https://github.com/XanaduAI/pennylane/pull/707 didn't seem too drastic in the `torch` interface:
image

I have to admit I'm not sure where the problem's coming from :thinking:

**Comment by josh146** [comment]
@trbromley 🤔 

I have to admit, this doesn't make much sense to me either. If something in #707 was causing an issue, I would think that it would either be (a) deterministic, (b) would not be numerical in nature, or (c) would differ wildly from the expected numerics

**Comment by josh146** [comment]
Oh, this seems vaguely familiar. @antalszava, wasn't there a bug you discovered a couple of months ago (perhaps a question on the forum?) where the PyTorch interface was differing in the 4th decimal place? If I recall, it was a very particular Torch edge case

**Comment by trbromley** [comment]
Had a quick chat with @antalszava who mentioned this issue: https://github.com/XanaduAI/pennylane/issues/534.

I also revisited the PR today to investigate if `torch.allclose()` would make sense, given that the tensors are originally in torch and then converted to numpy for the `allclose()` comparison. However, the errors still occurred (without a tolerance). There is also the option of `math.isclose()` but this is geared for scalars.

Note that I managed to increase the tolerance to `TOL = 1e-6` and the tests pass even with 1000 repetitions.

**Comment by trbromley** [comment]
To update: I still don't have an exact understanding of why https://github.com/XanaduAI/pennylane/pull/707 caused the problem, but the the error was coming from an `np.allclose()` comparison where one side was a numpy array in float64 and the other was a float32 torch tensor. This must have resulted in a small numeric inaccuracy.

The updated solution removes `TOL` and instead keeps everything as a torch32 tensor with a `torch.allclose()` comparison. I've rerun pytest using [pytest-repeat](https://pypi.org/project/pytest-repeat/) and don't have any problems with this fix.

**Comment by co9olguy** [comment]
Awesome, thanks for tracking this down @trbromley!
Good reminder to always use the correct framework when making numerical comparisons

**Pull request merged**
