### PR TITLE
`qml.state` and `qml.density_matrix` custom wires

### PR DESCRIPTION
**Pull request by antalszava**
**Context:**

When `qml.state` and `qml.density_matrix` have been added, custom wire labels have not yet been allowed.

Recent changes of creating the quantum information module and its density matrix capabilities have allowed a simple way for `qml.density_matrix` to add support.

**Description of the Change:**

* Removes the validation check that raises an error for custom wires;
* Maps the custom wire labels to device wires when computing the density matrix in `QubitDevice`.

**Benefits:**

Devices and circuits with custom wires labels are compatible with `qml.state` and `qml.density_matrix`.

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**

N/A

### CODE REVIEW

**Review by albi3ro — COMMENTED** [review]
No comments! Very happy to see this PR 🎉

**Review by albi3ro — APPROVED** [review]
sorry about forgetting the approval.

**Comment by antalszava** [comment]
No problem!

Overriding the check, it's failing due to the removed lines.

**Comment by antalszava** [comment]
[sc-17240]

**Pull request merged**
