### PR TITLE
Update Catalyst min version

### PR DESCRIPTION
**Pull request by rauletorresc**
**Context:** Moving from Catalyst v0.7.0 to v0.8.0 minimum version.

### CODE REVIEW

**Review by mudit2812 — APPROVED** [review]

**Comment by mudit2812** [comment]
@rauletorresc I assume this shouldn't get merged until after the release?

**Comment by astralcai** [comment]
This should be merged into PL-rc after the release of Catalyst and before the release of PL.

**Comment by rauletorresc** [comment]
> @rauletorresc I assume this shouldn't get merged until after the release?

It was not documented exactly when this should happen, but @astralcai is right. I have added those details into the documentation: https://github.com/PennyLaneAI/guidance-docs/blob/38391b87edfbe9b81454639695a2b7db48bcd266/development/catalyst-release.md?plain=1#L163

**Comment by astralcai** [comment]
> It was not documented exactly when this should happen, but @astralcai is right. I have added those details into the documentation: https://github.com/PennyLaneAI/guidance-docs/blob/38391b87edfbe9b81454639695a2b7db48bcd266/development/catalyst-release.md?plain=1#L163

This is actually part of the PennyLane release guide (https://github.com/PennyLaneAI/guidance-docs/blob/master/development/pennylane-release.md?plain=1#L424)

**Comment by rauletorresc** [comment]
Closing this PR so we keep the consistency in the release process on the PennyLane side. Also, the Catalyst release guide will be updated by removing this step from it. I guess @mudit2812 will create a similar PR next tuesday.

**Pull request closed without merging**
