### PR TITLE
Test backwards compatibility of autoray changes

### PR DESCRIPTION
**Pull request by eddddddy**
Make the changes in https://github.com/PennyLaneAI/pennylane/pull/4396 backwards compatible.

### CODE REVIEW

**Comment by eddddddy** [comment]
🤦

**Review by timmysilv — APPROVED** [review]
beautiful!!

**Review by mudit2812 — APPROVED** [review]

**Comment by trbromley** [comment]
The title of this PR doesn't seem to match the changes :thinking:

**Comment by eddddddy** [comment]
Yep, this PR was originally for testing and I forgot to update the name. I just updated the name to the same as the commit message of the merge commit into master: 7bc2e0ecaf97871ca8c00dba7bf265e7daa1df24.

**Pull request merged**
