### PR TITLE
create a PL-specific deprecation warning

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
When we deprecate features, it's hard to identify that we've done it.

**Description of the Change:**
Replace all deprecation warning categories with the new `PennyLaneDeprecationWarning`

**Benefits:**
We can add a pytest.ini filter to make this into failures on plugins!

```
[pytest]
filterwarnings =
    error::pennylane.PennyLaneDeprecationWarning
```

(I ran a test locally with a plugin that was setting `Observable.return_type` and saw that it raised the error)

**Possible Drawbacks:**
N/A

### CODE REVIEW

**Review by mudit2812 — APPROVED** [review]
Thanks! I like this change

**Review by albi3ro — COMMENTED** [review]
Worth adding a changelog entry, probably under deprecations, and a comment at the top of `deprecations.rst`

**Review by albi3ro — APPROVED** [review]
We should potentially have a follow up PR that adds the `pytest.ini` change to PennyLane itself, but that may take a bunch of test changes.

Hopefully this will make deprecations much cleaner 👍

**Comment by trbromley** [comment]
How will this change affect the user?
- Will the message they see be different?
- Will they have to update any functionality they have for filtering out warnings?

**Comment by albi3ro** [comment]
Message is the exact same. Only now the type says `PennyLaneDeprecationWarning` instead of `UserWarning`.  As it inherits from `UserWarning`, pre-existing filters will still work. It will just be easier to have finer under control over filtering the warnings.

Screenshot 2023-11-13 at 1 03 06 PM

**Pull request merged**
