### PR TITLE
Run black on tests

### PR DESCRIPTION
**Pull request by trbromley**
Runs `black -l 100` on all tests. Although running `black` is not compulsory on tests, it is still sometimes done (also by me, I like it!) and leads to a polluted diff.

(Everything in this PR is done automatically by `black` except for one change in 5b450c98983f6c88aec0aac5bf27923b71d4ab6f -- this was because `black` was giving an error for this test file due to an overindented `# fmt: off` on line 225.

### CODE REVIEW

**Review by antalszava — APPROVED** [review]
:100: Had a rough skim through, looks good! Would we like to start formatting tests too? :thinking: Maybe that would be a good thing if we feel there's some need for it.

**Review by josh146 — APPROVED** [review]
Thanks @trbromley!

Two thoughts:

- merging this PR may cause merge conflicts with open PRs that modify existing tests, however this should be easily solved by communicating to the authors to black the test suite before merging master.

- do we want to modify the `format.yml` GitHub action, to enforce that tests are also blacked?

I'm in favour of adding the tests to the black github action, as it it partly solve the former problem as well.

**Comment by trbromley** [comment]
Thanks, I have added `black -l 100 tests/` to the action!

**Comment by trbromley** [comment]
> merging this PR may cause merge conflicts with open PRs that modify existing tests, however this should be easily solved by communicating to the authors to black the test suite before merging master.

Right! Also when we merge this in, I can go through the recent PRs and make sure they are up to date. Might hold off merging this in until after release :+1:

**Comment by josh146** [comment]
> Right! Also when we merge this in, I can go through the recent PRs and make sure they are up to date. Might hold off merging this in until after release 👍

I'll merge this in right after the v0.16-dev bump :)

**Pull request merged**
