### PR TITLE
Fix logging trace statement with empty gradient_fn

### PR DESCRIPTION
**Pull request by mlxd**
### Before submitting

Please complete the following checklist when submitting a PR:

- [x] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [x] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [x] Ensure that the test suite passes, by running `make test`.

- [x] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [x] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:** The logging implementation for the TRACE level assumes the existence of several functions to report their source when enabled. If the gradient_fn is None, the logger attempts to retrieve the source and fails.

**Description of the Change:** This adds an existence check for all execute-enabled TRACE level log statements, and reports only if the associated functions exist.

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by mlxd** [comment]
[sc-47564]

**Review by timmysilv — COMMENTED** [review]
not sure I totally get what's being handled here. I thought it was the difference when `gradient_fn` is None, but they seem the same?

```pycon
>>> def fn1():
...     return 2
>>> fn2 = None
>>> print(isfunction(fn1), isfunction(fn2))
True False
>>> print(callable(fn1), callable(fn2))
True False
```

**Review by mudit2812 — COMMENTED** [review]
I think some minimal testing would be good, since this was never caught by CI, otherwise looks good!

**Comment by mlxd** [comment]
> not sure I totally get what's being handled here. I thought it was the difference when `gradient_fn` is None, but they seem the same?
> 
> ```
> >>> def fn1():
> ...     return 2
> >>> fn2 = None
> >>> print(isfunction(fn1), isfunction(fn2))
> True False
> >>> print(callable(fn1), callable(fn2))
> True False
> ```

Did you enable the trace logging level? This config requires explicit edits to the YAML file at https://github.com/PennyLaneAI/pennylane/blob/4e71a8f49db836f83b6c387856ce8feb1deae5b8/pennylane/logging/log_config.toml#L86

I see failures without this, and success with.

**Comment by mlxd** [comment]
> I think some minimal testing would be good, since this was never caught by CI, otherwise looks good!

Testing with the previous logging contribution wasn't easily possible, so this will likely need to be skipped.

**Review by mudit2812 — APPROVED** [review]
Thanks!

**Review by timmysilv — APPROVED** [review]
talked offline, looks good 👍

**Pull request merged**
