### PR TITLE
bump torch version

### PR DESCRIPTION
**Pull request by albi3ro**
### Before submitting

Please complete the following checklist when submitting a PR:

- [ ] All new features must include a unit test.
      If you've fixed a bug or added code that should be tested, add a test to the
      test directory!

- [ ] All new functions and code must be clearly commented and documented.
      If you do make documentation changes, make sure that the docs build and
      render correctly by running `make docs`.

- [ ] Ensure that the test suite passes, by running `make test`.

- [ ] Add a new entry to the `doc/releases/changelog-dev.md` file, summarizing the
      change, and including a link back to the PR.

- [ ] The PennyLane source code conforms to
      [PEP8 standards](https://www.python.org/dev/peps/pep-0008/).
      We check all of our code against [Pylint](https://www.pylint.org/).
      To lint modified files, simply `pip install pylint`, and then
      run `pylint pennylane/path/to/file.py`.

When all the above are checked, delete everything above the dashed
line and fill in the pull request template.

------------------------------------------------------------------------------------------------------------

**Context:**

**Description of the Change:**

**Benefits:**

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Review by mudit2812 — APPROVED** [review]

**Comment by mudit2812** [comment]
Torch tests are failing.

**Comment by albi3ro** [comment]
[sc-47037]

**Comment by timmysilv** [comment]
backwards AD fails with torch jacobian computations of functions with complex return type. See pytorch/pytorch#94397 for details. I changed the apply_operation RX tests to use forward-mode AD and it worked.

I marked the rest of the tests with xfail because they did not support forward-mode for one of two reasons:
1. multi-dimensional return values (eg. density matrix) fail saying "RuntimeError: Batching rule not implemented for aten::item. We could not generate a fallback"
2. functions without a jvp defined fail saying "NotImplementedError: You must implement the jvp function for custom autograd.Function to use it with forward mode AD."

Is xfail the best choice here? idk what else to do.

**Comment by albi3ro** [comment]
I can't approve since I originally opened this, but 👍 from me.

**Review by timmysilv — APPROVED** [review]

**Pull request merged**
