### PR TITLE
get op batch size at runtime to match DQL

### PR DESCRIPTION
**Pull request by timmysilv**
**Context:**
Found this issue while checking if KerasLayer works with DQ2 yet (spoiler alert - it does not).

We tried to be more elegant with DQ2 regarding batch sizes, and that was good and all. The only problem is, `Operator._check_batching` has a whole bunch of problems with TF-Autograph (just check [the inline comments](https://github.com/PennyLaneAI/pennylane/blob/2d1f6a395fde6bf6a9bbe1aeba6945882760704c/pennylane/operation.py#L1073-L1090)). The whole thing is just a mess, so after discussion with @rmoyard we felt it would be best to mimic DQL's behaviour here.

tl;dr TF-Autograph has taught me that we _should_ check batch sizes at run-time, not "compile" (aka preprocess)-time.

**Description of the Change:**
Check operator batch size at runtime during `apply_operation`.

**Benefits:**
It needs to be done to make `KerasLayer` work

**Possible Drawbacks:**
- This will slow things down fairly severely. Perhaps we can make a smarter move in the future, but I just want something that works for now. To be clear, this performance change puts us at parity with DQL
- I checked locally, and [one KerasLayer test](https://github.com/PennyLaneAI/pennylane/blob/2d1f6a395fde6bf6a9bbe1aeba6945882760704c/tests/qnn/test_keras.py#L641) is still failing with DQ2 whenever `output_dim` > 1 because for some reason, when re-loading the QNN from file it assumes the abstract batch size (`None`) is `1`, but it should be `None` (so Autograph can decide on the value at runtime)

### CODE REVIEW

**Review by mudit2812 — COMMENTED** [review]
The changes look good to me. If the performance hit is as severe as you say, I think @trbromley should take a look before I approve.

**Comment by trbromley** [comment]
> This will slow things down fairly severely. Perhaps we can make a smarter move in the future, but I just want something that works for now.

Will this be a slowdown across the board, or more specific to TF-related runs?

> To be clear, this performance change puts us at parity with DQL

If this is the case then it's fine - all we want at this stage is feature and performance parity.

**Comment by timmysilv** [comment]
across the board, but yes it'll put us at parity. DQL would [always get the batch size from the matrix](https://github.com/PennyLaneAI/pennylane/blob/99b4856b85d02d05c9fedb570a7320406c59f45f/pennylane/devices/default_qubit.py#L873) (and not from the operator property), so now we do it here too.

**Review by mudit2812 — APPROVED** [review]

**Review by rmoyard — APPROVED** [review]
Thanks @timmysilv a lot of effort to find the issue :100:

**Pull request merged**
