### PR TITLE
Define the generator for the MultiRZ operation

### PR DESCRIPTION
**Pull request by josh146**
**Context:**

* For the metric tensor computation, all parametrized gates must provide their generator. If a gate does not provide its generator, the metric tensor computation will raise an error.

* The `qml.MultiRZ` gate allows us to very efficiently implement `exp(-i θ Z ⊗ Z ⊗ ... ⊗  Z/2)` on simulator devices, since it is a diagonal in the computational basis. However, if a device does not support `qml.MultiRZ`, the operation on `N` wires simply gets decomposed into `2N-2` CNOTs and a single RZ.

* `qml.MultiRZ` does not provide a generator. Therefore, when using the `QNGOptimizer`, one of two things could happen:

  1. The device supports `MultiRZ` natively: QNG optimization will fail since the generator is unknown
  2. The device does not support `MultiRZ` natively: QNG optimization will work, since the decomposition results in an `RZ` gate, which *does* have its generator defined.
 
**Description of the Change:**

* Defines the generator of the `MultiRZ` gate as a diagonal numeric matrix.

**Benefits:**

* Circuits which contain `qml.MultiRZ` can now be used with QNG optimization, regardless of whether the device natively supports it or not.

**Possible Drawbacks:**

* Since the generator is numeric, if `MultiRZ` is applied to N qubits, a `2**N` matrix for the generator will be created. This obviously scales **really** badly. It would probably be better on `default.qubit` to simply force decomposition of the `MultiRZ` gate, rather than use this fix.

In fact, the entire metric tensor code is quite old and due for a re-write. In particular, we should:

* Have all operations provide Hamiltonians of Pauli operators as generators, and avoid numeric matrices

* For each block diagonal of the metric tensor, the diagonalization should be done systematically using the `qml.grouping` module, rather than numerically.

**Related GitHub Issues:** n/a

### CODE REVIEW

**Comment by trbromley** [comment]
Thanks @josh146!

I am in favour of merging this PR despite the drawbacks you mention - it unlocks functionality that could not be accessed before and will not result in any UI changes if we overhaul the metric tensor code behind the scenes.

Is there a way we could cache the generator to prevent it being calculated each iteration step, e.g.,
```python
if self._generator is None:
    self._generator = [np.diag(pauli_eigs(len(self.wires))), -1/2]

return self._generator
```

**Comment by josh146** [comment]
> Is there a way we could cache the generator to prevent it being calculated each iteration step, e.g.,

Good idea!

However, I'm not sure how much of a difference this might make, since the matrix could be very large, so simply storing it will be an issue.

Long term, we should re-structure this to simply return

```python
[qml.operations.Tensor(*[qml.PauliZ(w) for w in self.wires]), -1/2]
```

(not possible at the moment, since the existing generator logic expects the first element to be a class (`qml.PauliZ`) or a matrix, _not_ an instance.

**Review by trbromley — APPROVED** [review]
I approve, but made some significant additions/changes, so would be good for @josh146 or @thisac to check too.

**Review by josh146 — COMMENTED** [review]
I can't approve, but looks good to me!

**Pull request merged**
