### PR TITLE
Set `grad_method=None` for `ControlledSequence`, `Reflection`, `AmplitudeAmplification`, and `Qubitization`.

### PR DESCRIPTION
**Pull request by astralcai**
**Context:**
Templates that are not actually supported by `parameter_shift` should have `grad_method=None` so that they are decomposed by `_expand_transform_param_shift`

**Description of the Change:**
1. Adds the `data` of components of the templates to the `data` of the templates such that trainable parameters are tracked
2. Adds `grad_method=None` for `ControlledSequence`, `Reflection`, `AmplitudeAmplification`, and `Qubitization`.

**Related GitHub Issues:**
Fixes https://github.com/PennyLaneAI/pennylane/issues/5802
[sc-64967]

### CODE REVIEW

**Comment by trbromley** [comment]
CC @KetpuntoG

**Comment by KetpuntoG** [comment]
> CC @KetpuntoG

`ControlledSequence`, `AmplitudeAmplification` and `Reflection` from a theoretical point of view should be differentiable with parameter shift rule. Is this PR due to a PL limitation?

**Comment by astralcai** [comment]
> > CC @KetpuntoG
> 
> `ControlledSequence`, `AmplitudeAmplification` and `Reflection` from a theoretical point of view should be differentiable with parameter shift rule. Is this PR due to a PL limitation?

I've done some investigation but haven't found out why directly taking parameter shift on the templates return incorrect results.

**Comment by albi3ro** [comment]
> > CC @KetpuntoG
> 
> `ControlledSequence`, `AmplitudeAmplification` and `Reflection` from a theoretical point of view should be differentiable with parameter shift rule. Is this PR due to a PL limitation?

To clarify, this doesn't say "don't use parameter shift with these templates".  It is "decompose before applying parameter shift".

Theoretically, we could develop parameter shift rules for the templates and add them to the `grad_recipe`. But that seems like a lot of unnecessary work when we can just decompose them. Since this is fixing a bug where pennylane is giving wrong answers and blocking a P0, we should proceed with this fix for now.  But if you are interested in developing a customized parameter shift recipe for the templates, I am willing to support.

Would there be a benefit to being able to natively apply parameter shift to these templates instead of to their decomposed form?  For some templates, like `CommutingEvolution`, it might lead to fewer total parameter shift tapes.

**Comment by KetpuntoG** [comment]
> > > CC @KetpuntoG
> > 
> > 
> > `ControlledSequence`, `AmplitudeAmplification` and `Reflection` from a theoretical point of view should be differentiable with parameter shift rule. Is this PR due to a PL limitation?
> 
> To clarify, this doesn't say "don't use parameter shift with these templates". It is "decompose before applying parameter shift".
> 
> Theoretically, we could develop parameter shift rules for the templates and add them to the `grad_recipe`. But that seems like a lot of unnecessary work when we can just decompose them. Since this is fixing a bug where pennylane is giving wrong answers and blocking a P0, we should proceed with this fix for now. But if you are interested in developing a customized parameter shift recipe for the templates, I am willing to support.
> 
> Would there be a benefit to being able to natively apply parameter shift to these templates instead of to their decomposed form? For some templates, like `CommutingEvolution`, it might lead to fewer total parameter shift tapes.

Ah okey! That's perfect: first decompose,  then shift-rule
Thanks for the clarification

**Review by KetpuntoG — APPROVED** [review]
Thanks! It looks good to me :)

**Review by dwierichs — APPROVED** [review]
Looks good to me! :tada: Thanks!

**Pull request merged**
