### PR TITLE
Change `Operator.num_wires` to `AnyWires`

### PR DESCRIPTION
**Pull request by mudit2812**
Change `Operator.num_wires` from an abstract value to `AnyWires`. This will make adding new operators slightly easier if the operator acts on arbitrary wires.

### CODE REVIEW

**Comment by mudit2812** [comment]
[sc-34241]

**Comment by timmysilv** [comment]
do we worry that someone will forget to define it for a new Operator, although they should have? and if they forgot, what might the consequences be? For example, imagine we didn't set `num_wires` on PauliX. Today, it fails to create something like `qml.PauliX(wires=[0, 1])`, and that's good because that wouldn't make sense! With this change, that operator would exist just fine, though how it behaves would depend on implementation.

**Comment by albi3ro** [comment]
> do we worry that someone will forget to define it for a new Operator, although they should have? and if they forgot, what might the consequences be? For example, imagine we didn't set `num_wires` on PauliX. Today, it fails to create something like `qml.PauliX(wires=[0, 1])`, and that's good because that wouldn't make sense! With this change, that operator would exist just fine, though how it behaves would depend on implementation.

The documentation for creating `Operator`'s still says to define `num_wires`, and all of our operators still explicitly define them. In a case like `PauliX`, we know its important to validate the number of wires, and so we will define it. This will just make it easier to define templates and other very permissive operators.

**Review by albi3ro — COMMENTED** [review]
I don't know why pylint is complaining, but that will need to be solved.

I'll approve once pylint is passing. We have given all relevant people notice of a change to `Operator`, and people seem to like the idea, so I don't think we need to wait any more on that.

**Comment by timmysilv** [comment]
pylint is complaining because those classes used to inherit the docstring from `Operator.num_wires`, but now the parent value is an attribute, not a property (method).

**Comment by mudit2812** [comment]
I've changed `Operator.num_wires` to a property, but this creates a breaking change.

If I make `Operator.num_wires` a property, then any operator that inherits it that doesn't define `num_wires` will need to be instantiated first to use `op.num_wires` and actually get a correct value back. This does not affect any current PL ops because all of them set `num_wires`, but it might affect ops added in the future.

I've always found it very helpful to be able to access `num_wires` without having to instantiate the operator, and if that changes now it could break some functionality. In that case, if I were to create a new op `Dummy` that has `num_wires = AnyWires` by default but I choose not to specify that when I implement the op, `Dummy.num_wires` would return a `property`, while `Dummy().num_wires` would return `AnyWires`.

**Review by albi3ro — APPROVED** [review]
Looks good 👍

**Pull request merged**
