### PR TITLE
[BUGFIX] Disallow applying gradient transforms to broadcasted tapes

### PR DESCRIPTION
**Pull request by dwierichs**
**Context:**
As reported in #4462, differentiating broadcasted tapes with gradient transforms is not supported when using a ML entrypoint or calling the transform on the QNode directly.
This is due to a mismatch between the assumed and the factual output of gradient transforms called on a broadcasted tape, see the issue for details.

**Description of the Change:**
This PR disallows applying the gradient transforms to broadcasted tapes explicitly, for each transform.
This will allow us to implement the correct output structure for each transform individually, allowing for a modular update.

**Benefits:**
Clear error message instead of cryptic error in use cases like the one in #4462

**Possible Drawbacks:**
Applying gradient transforms to broadcasted tapes on the tape level actually is fine, and this PR removes the support of this feature. This is not too bad if we get back to implementing the feature on the QNode level soon enough.

**Related GitHub Issues:**
#4462

### CODE REVIEW

**Review by mudit2812 — APPROVED** [review]

**Review by mudit2812 — CHANGES_REQUESTED** [review]
The changes look good, but old tests need to be updated to catch this error as well. Happy to approve once fixed 😄

**Comment by dwierichs** [comment]
Ah, missed the JVP and legacy tests. 
Should be fixed now.

**Review by albi3ro — APPROVED** [review]
Thanks!

**Review by mudit2812 — APPROVED** [review]
Great! Thanks David

**Pull request merged**
