### PR TITLE
Correct Typo in qml_templates.rst

### PR DESCRIPTION
**Pull request by kylegodbey**
**Context:** Typo in documentation

**Description of the Change:** Fixed the offending misspelling of Preparation

**Benefits:** Correctness

### CODE REVIEW

**Review by co9olguy — APPROVED** [review]

**Comment by co9olguy** [comment]
Nicely spotted, thanks @kylegodbey!

**Comment by co9olguy** [comment]
If you like, you can add yourself as a contributor to the changelog before we merge this PR :)

**Comment by kylegodbey** [comment]
Thanks! I modified the changelog and now the bots are happy

**Comment by co9olguy** [comment]
Perfect, thanks for the contribution!

**Pull request merged**
