### PR TITLE
Remove circuit hash setting in `QubitDevice`

### PR DESCRIPTION
**Pull request by antalszava**
**Context:**
The `QubitDevice.execute` method computes a hash for the quantum circuit by using the `hash` attribute of the underlying `CircuitGraph`: `circuit.graph.hash` (where `circuit` is a `QuantumTape` object). This can, however, introduce overhead if the `CircuitGraph` was not built previously.

**Description of the Change:**
Removes the circuit hash creation from `QubitDevice.execute`. Plugin devices that require a hash for a quantum circuit should compute the hash in the plugin itself (e.g., `PennyLane-Forest` for parametric compilation).

**Benefits:**
The `CircuitGraph` is not constructed while creating a circuit hash.

**Possible Drawbacks:**
N/A

**Related GitHub Issues:**
https://github.com/PennyLaneAI/pennylane/issues/1180

### CODE REVIEW

**Comment by antalszava** [comment]
Locally have `pennylane/_qubit_device.py                                                262      0   100%` as a result of `make coverage`.

**Comment by josh146** [comment]
> Locally have pennylane/_qubit_device.py 262 0 100% as a result of make coverage.

This feels like something codecov should be a lot smarter about 🤔

**Review by josh146 — APPROVED** [review]
@antalszava happy to approve this, since merging it in will result in a speedup compared to master.

However, we should make an issue to remind us to:

- Move the hash to a property of the tape
- Re-add the removed tests.

Should we keep the tests for now, just mark them as xfail?

**Comment by antalszava** [comment]
@josh146 makes sense! Opened up https://github.com/PennyLaneAI/pennylane/issues/1187. It seems that tests here are `QubitDevice` specific, linked this PR in the issue so that they can be ported to `QuantumTape` once that issue is tackled.

**Pull request merged**
