### PR TITLE
Update Docker Plugins

### LINKED ISSUE #4123: Update plugins in Docker builds
### Feature details

[Building of PennyLane images in Docker](https://docs.pennylane.ai/en/stable/development/guide/installation.html#docker) is supported, including [optional installation of the plugins](https://github.com/PennyLaneAI/pennylane/blob/b568abf5b89f97b5e77a7ecb71594afef9b1541d/docker/Makefile#L15). We would like to update the available plugins to:
- Remove [PL-SF](https://docs.pennylane.ai/projects/strawberryfields/en/latest/) because this is no longer supported in version 0.30 and above.
- Add the new [Quantum Inspire](https://pennylane-quantuminspire.readthedocs.io/en/latest/) plugin

### Implementation

The changes will occur in [install_plugin.sh](https://github.com/PennyLaneAI/pennylane/blob/master/docker/plugins/install-plugin.sh) and the [Makefile](https://github.com/PennyLaneAI/pennylane/blob/master/docker/Makefile).

Optionally, we would also like to update the [interface versions](https://github.com/PennyLaneAI/pennylane/blob/master/docker/interfaces/install-interface.sh) to match those [used in the CI](https://github.com/PennyLaneAI/pennylane/blob/master/.github/workflows/tests.yml).

### How important would you say this feature is?

1: Not important. Would be nice to have.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by manulpatel**
**Context:**
Updates to docker plugins. 

**Description of the Change:**
1. Removed [PL-SF](https://docs.pennylane.ai/projects/strawberryfields/en/latest/) plugin.
2. Added the new [Quantum Inspire ](https://pennylane-quantuminspire.readthedocs.io/en/latest/)plugin.
3. Updated the interface versions to that in CI.

**Related GitHub Issues:**
Closes #4123

### CODE REVIEW

**Comment by trbromley** [comment]
Thanks @manulpatel! :rocket:

We'll take a look and give some feedback soon!

**Review by timmysilv — COMMENTED** [review]
Hi @manulpatel, this looks great! can you make the equivalent changes to `install-interface-gpu.sh` as well? Otherwise this PR is good to go in my books 😄 

PS - have you built any of the docker images you're touching to verify that your changes work? I know it's tough to test changes like these without formal tests written, so manual testing will do just fine. Thanks!

**Comment by manulpatel** [comment]
Hi @timmysilv! Thanks for reviewing. Sure I will update in  `install-interface-gpu.sh` as well. But could you please give any hints on whether I need to change `jax==0.2.14 jaxlib==0.1.67+cuda111` version? I might be missing if this specific version is serving some internal dependency. In `install-interface.sh`, the latest version of `jax `was used, so didn't encounter this.

**Comment by timmysilv** [comment]
jax is usually a tricky one, so that's understandable. They change frequently, so we change with them! I'd say make it unpinned in both to stay up-to-date. Note that the GPU script will need the GPU version of jax(lib) - see [their docs](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier) on that for what to do

**Comment by manulpatel** [comment]
I have kept `jax` versions to latest in both. But in gpu script, `jaxlib `is set to the said version as required by cuda111.

**Comment by timmysilv** [comment]
the jaxlib version also needs to be more recent (probably 0.4.10), so pinning to an old version will not work either. If the GPU installation instructions require a specific version for jaxlib (in order to add the `+cuda11` suffix), then definitely go ahead and do it 😄 

Some hints:
- Our [installation guide](https://docs.pennylane.ai/en/stable/development/guide/installation.html#build-a-pennylane-image-with-a-specific-interface) gives you the command to build a docker image using a specific interface and a GPU
- The [base image being used](https://github.com/PennyLaneAI/pennylane/blob/8b5b92b0158d5f7281c3d36a35e06b8c993f1e90/docker/interfaces/gpu-cuda/cuda-base.dockerfile#L15) seems outdated, and might need upgrading
- If you must specify a version for Jax(lib), use `0.4.10`, as PennyLane is not compatible with older versions anymore

**Review by timmysilv — COMMENTED** [review]
were you able to verify if the build passes locally using `make -f docker/Makefile build-interface-gpu interface-name=jax`?

**Comment by timmysilv** [comment]
Hi again, thanks for bearing with me. The docker builds were not in a functional state for many reasons beyond the scope of the Unitary Hack issue you're trying to solve. Although the docker image still won't build after this PR, you've certainly addressed what's asked of the issue 💪 Go ahead and merge this (once we get you a second review), and we'll take care of the rest to get docker builds working again. Happy hacking!

**Review by timmysilv — APPROVED** [review]

**Review by rmoyard — APPROVED** [review]
Thanks for your contribution !

**Comment by manulpatel** [comment]
Thanks @timmysilv @rmoyard for approval. I am a QIC enthusiast majoring in Physics and really look forward to contributing to Pennylane outside Unitary Hack.

**Comment by timmysilv** [comment]
awesome, looking forward to all your new features! non-hackathon development is pretty similar, but be sure to check out our [contribution guide](https://docs.pennylane.ai/en/stable/development/guide/contributing.html) before getting started. Merging this now, and voila - you're a contributor 😸

**Comment by manulpatel** [comment]
Yes it would be very nice of you. You may write "Manul Patel". Thanks @trbromley!

**Comment by trbromley** [comment]
Thanks, done: 32e3db3f208f5e3989a3e74243455b2a44f13385

**Pull request merged**
