### PR TITLE
use ctrl helper instead of self.__class__

### PR DESCRIPTION
**Pull request by timmysilv**
While this makes little difference today, it will allow for child classes to have different constructor definitions then put custom logic in `qml.ctrl`. Those helper functions (like `qml.prod` and `qml.sum`) exist to have custom dispatching and other wrapper-related stuff, so it makes sense to put this there.

The concrete examples down the road are CZ and CY, which don't have a base in their constructor (it's always Z or Y), so the custom dispatching will go into `qml.ctrl`, and the functions being touched in this PR won't break for them!

Discussion started in [this comment](https://github.com/PennyLaneAI/pennylane/pull/4117/files#r1196768454) on the CZ update PR

### CODE REVIEW

**Comment by frederikwilde** [comment]
Looks good to me and it works for `CY` as implemented in #4116, without the re-implementation of the `pow`, `simplify`, or `adjoint` methods.

The extra return branch in `ctrl` would have to be
```Python
if isinstance(op, tuple(no_base_ops)):
        return no_base_ops[type(op)](control + op.wires)
```
to include the control wires. Also, `isinstance` doesn't accept sets. I don't understand why.

However, I get an error when simplifying a CCY gate:
```Python
cy = qml.CY([0, 1])
ccy = ctrl(cy, 2)
ccy.simplify()
```
throws a `ValueError: too many values to unpack (expected 2)`, since `control` now contains two wires.

**Review by frederikwilde — COMMENTED** [review]
Looks good to me and it works for `CY` as implemented in #4116, without the re-implementation of the `pow`, `simplify`, or `adjoint` methods.

The extra return branch in `ctrl` would have to be
```Python
if isinstance(op, tuple(no_base_ops)):
    return no_base_ops[type(op)](control + op.wires)
```
to include the control wires. Also, `isinstance` doesn't accept sets. I don't understand why.

However, I get an error when simplifying a CCY gate:
```Python
cy = qml.CY([0, 1])
ccy = ctrl(cy, 2)
ccy.simplify()
```
throws a `ValueError: too many values to unpack (expected 2)`, since `control` now contains two wires.

**Review by BorjaRequena — APPROVED** [review]
Looks good! Exactly what we needed :D

**Review by mudit2812 — APPROVED** [review]
I'm quite happy with this change. Just a reminder for @frederikwilde and @BorjaRequena to update their PRs accordingly.

**Comment by timmysilv** [comment]
@frederikwilde that is concerning but more related to the CY/CZ changes imo. I'm only proposing an idea here, not necessarily the correct, functional code. Should CY and CZ support multiple control wires/control values? I got the sense that we don't want that, so perhaps the conditional should be if the base is `PauliY` _and_ `len(control) == 1`

**Pull request merged**
