### PR TITLE
Deprecate `QubitDevice`'s caching

### PR DESCRIPTION
**Pull request by antalszava**
**Context**

The `QubitDevice` class provides the ability to store device executions in a cache. With the latest versions of QNodes, caching is available on the QNode level too.

By default, QNode caching will only create the cache per QNode call/execution. So the default caching behaviour will cache all repeated circuit evaluations during a single call.

For example, a single call might cause multiple circuits internally for the parameter-shift rule; circuits that end up being identical will not be re-executed, simply the cached result will be retrieved.

This is deliberate, as users expect different results to be returned when shot noise is present (see discussion here https://github.com/PennyLaneAI/pennylane/issues/2150). However, it is possible to change this behaviour. If a user creates a cache manually and pass this to the QNode, the QNode will keep using this cache object for separate evaluations:

```python
dev = qml.device('default.qubit', wires=nwires)
​
cache = {}
​
@qml.qnode(dev, diff_method='parameter-shift', cache=cache)
def expval_circuit(params):
    qml.templates.BasicEntanglerLayers(params, wires=wires, rotation=qml.RX)
    return qml.expval(qml.Hermitian(hamiltonian, wires=wires))
​
@qml.qnode(dev, diff_method='parameter-shift', cache=cache)
def var_circuit(params):
    qml.templates.BasicEntanglerLayers(params, wires=wires, rotation=qml.RX)
    return qml.var(qml.Hermitian(hamiltonian, wires=wires))
​
>>> print(expval_circuit(params), var_circuit(params)))
-2.6224875809703287, 0.011605015096940896
>>> print(cache)
{-2104543859499562169: array([-2.62248758]), 3268478774057874589: array([0.01160502])}
>>> print(expval_circuit(params), var_circuit(params)))  # evaluate QNodes again
-2.6224875809703287, 0.011605015096940896
>>> dev.num_executions  # only the first two executions will register
2
```

image (10)

**Changes**

* Places a deprecation warning in the `QubitDevice` class mentioning that the caching ability of the class is being deprecated.

**Benefits**

Moving towards having a single way of solving the same issue.

**Note**

Likely the `dev.num_execution` has to be adjusted when using `diff_method="backprop"` because multiple executions are recorded whereas the cache itself is being populated and used:
Screenshot from 2022-02-02 14-54-03

### CODE REVIEW

**Review by Jaybsoni — APPROVED** [review]
Looks good! I guess the only thing to check would be if we are using caching anywhere else in the tests. Since the tests are passing I assume there are no other instances in tests where caching is being implicitly used.

**Comment by josh146** [comment]
> Likely the dev.num_execution has to be adjusted when using diff_method="backprop" because multiple executions are recorded whereas the cache itself is being populated and used:

I wonder if [`qml.Tracker`](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Tracker.html) is also affected?

**Comment by antalszava** [comment]
[sc-14402]

**Comment by antalszava** [comment]
Note: I'd like to merge this PR iff https://github.com/PennyLaneAI/pennylane/pull/2171 has been merged. That PR fixes a bug with QNode caching when recording the number of executions.

**Comment by antalszava** [comment]
> I wonder if [qml.Tracker](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.Tracker.html) is also affected?

I don't think so, as the issue was inside of `qml.QNode`. Tracking happens on the device level.

**Pull request merged**
